### ISSUE TITLE
Combinations are wrong if n = 0

### ISSUE THREAD

**Issue by chowdhurya** [sithmel/iter-tools#1]
The only combination of any set for n = 0 should be the empty set, but iter-tools returns the complete set instead. An example showing the difference between Python's itertools library and this one is shown below.

```
$ python
>>> from itertools import combinations
>>> list(combinations(["A", "B", "C", "D"], 0))
[()]
```

```
$ node
> combinations = require('iter-tools/lib/combinations')
[GeneratorFunction: combinations]
> Array.from(combinations(["A", "B", "C", "D"], 0))
[ [ 'A', 'B', 'C', 'D' ] ]
```

I have not tested to see if the other functions, such as permutations, have this problem, but I suspect that they do.

**Comment by sithmel** [comment]
Thanks for noticing that, I'll have a look asap

**Comment by sithmel** [comment]
fixed
