### ISSUE TITLE
fromStream and asyncPipeline

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#100]
I am picking up this 2 from https://github.com/bustle/streaming-iterables

**fromStream** is a compatibility layer to add a async-iterable interface where there is a stream.

**pipeline** is a syntactic sugar for using compose. It is more intuitive and readable.

**Comment by KSXGitHub** [comment]
> **fromStream** is a compatibility layer to add a async-iterable interface where there is a stream.

Well, I needed this months ago, I didn't know where to find it, so I had to created by myself (same function name BTW), now that you also decide to add it to `iter-tools`, this would cause a lot of duplication.



> **pipeline** is a syntactic sugar for using compose. It is more intuitive and readable.

Totally agree.

**Comment by sithmel** [comment]
@KSXGitHub still pondering if I want to add fromStream here, or in some other package. Maybe iter-tools-node-compat or something like that ? Did you have yours somewhere ? 
Also writestream looks like a good idea in the same package https://github.com/bustle/streaming-iterables#writetostream

**Comment by KSXGitHub** [comment]
> Did you have yours somewhere ?

Yes, it is called [`iterate-evented-stream`](https://github.com/ksxnodeapps/fun-little-utilities/tree/master/packages/iterate-evented-stream)
