### ISSUE TITLE
find() should return undefined instead of null when item is not found

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#105]
Since [`Array.prototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) returns `undefined` when item is not found.

I think it is better to not confuse users by deviating from standard.

**Comment by sithmel** [comment]
@conartist6 any reason why we are returning "null" when an item is not found ?
I think we should return undefined

**Comment by conartist6** [comment]
Sounds good

**Comment by sithmel** [comment]
I would proceed.Given that the documentation didn't specify the old behaviour, I would consider it a bug fix. Any objection ?

**Comment by KSXGitHub** [comment]
Bug fix it is.

**Comment by KSXGitHub** [comment]
@sithmel _GitHub tip:_ You can make GitHub close an issue automatically by commenting `Fixes <link to the issue>` (or `Fix <link>`) in the Pull Request. When you do this, a `close by <pull request>` should appear in the bottom of said issue.
