### ISSUE TITLE
Suggestion: compare method

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#107]
```js
compare([1, 2, 3], [1, 2, 3]) // true
```

Open questions:
- Should it allow more than two iterables to be compared at once?
- Should it allow a custom comparator to be passed?
- Should it recurse when individual items are also iterables?

**Comment by sithmel** [comment]
Should it allow more than two iterables to be compared at once? **it would be almost for free, so why not**
Should it allow a custom comparator to be passed? **an optional one. Ok**
Should it recurse when individual items are also iterables? **No. the custom comparator can take care of this case**

**Comment by conartist6** [comment]
I definitely don't think recursion should be the responsibility of the custom comparator. But perhaps there should be a compare and a deepCompare?

**Comment by KSXGitHub** [comment]
"compare" might be "greater/less than" or "equal"

**Comment by KSXGitHub** [comment]
I also think custom comparator can take care of recursive comparison.

**Comment by sithmel** [comment]
A toy implementation:
```js
function compare (iter1, iter2) {
  return every(([item1, item2]) => item1 === item2, zipLongest(iter1, iter2))
}
```

**Comment by KSXGitHub** [comment]
I think `Object.is` should be the default comparator

**Comment by sithmel** [comment]
Given that the implementation using existing function is straightforward, I would close
