### ISSUE TITLE
Supporting truly infinite iterables

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#113]
While working on the factorial implementation (used to calculate combination length), I verified that the claim that we support "infinite sequences" is not entirely true.

In many cases we rely on using a counter that is basically a double with a maximum precision of [2^53-1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

We could fix this problem using (optionally) [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

This is currently a stage 3 proposal, so it is very likely it will be a part of the language soon.

**Comment by conartist6** [comment]
You are concerned that someone will want to use an iterable with more than one quadrillion items?

**Comment by sithmel** [comment]
The use case I had in mind are:
* long running tasks
* brute force that can last several days

Still, even in those cases I am not sure this is really needed.

So far the only thing that fails easily is calculating the lengths of combinatory iterables: operations involving factorials lose precision very easily, even if the final result is a double.

Something like this:
```js
return factorial(len) / (factorial(r) * factorial(len - r))
```
should be calculated using BigInt and then converted to Number before returning. Or maybe there is a more reasonable formula ?

**Comment by sithmel** [comment]
I have fixed the factorial issue with this commit https://github.com/sithmel/iter-tools/commit/6494104af17519ed7af5b4db6b0d68d1f4bf558c

I would say that 2^53 is a reasonably upper bound for now

**Comment by sithmel** [comment]
I have fixed the factorial issue with this commit https://github.com/sithmel/iter-tools/commit/6494104af17519ed7af5b4db6b0d68d1f4bf558c

2^53 is a reasonable upper bound for now
