### ISSUE TITLE
Suggestion: change 'length' getter of combinatory function to 'getLength()' function

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#115]
## Reasons

**Principle of least astonishment:** Properties in JavaScript are expected to be fast to access, but the [current `length` getter](https://github.com/sithmel/iter-tools/pull/108) invokes `factorial` function which is an `O(n)` operation. Changing it to a function makes it explicit. (For reference, in Rust, slow operations are explicit)

**Comment by KSXGitHub** [comment]
Factorials are cached, but still `O(n)` for the first time of each `n`.

**Comment by sithmel** [comment]
"of each n": no:
if you have calculated 20! and you want to calculate 21!, you are one multiplication away from the result

**Comment by KSXGitHub** [comment]
I still want it to be explicit, since first run still affects performance.

Beside, https://github.com/sithmel/iter-tools/blob/dc0a951033131ef11388012dbb9eb33275d3a39e/src/product.mjs#L24-L31 is for sure `O(n)`

**Comment by sithmel** [comment]
that "n" is the number of iterables you are passing the product function. If you are concerned about that, you should be concerned instead that your sequence won't fit in memory.

> First run still affects performance

20! is already 2.432902e+18 that is bigger than Number.MAX_SAFE_INTEGER

So with even small "n" the concern is precision. Not speed

**Comment by KSXGitHub** [comment]
> 20! is already 2.432902e+18 that is bigger than Number.MAX_SAFE_INTEGER

You just convinced me about https://github.com/sithmel/iter-tools/issues/113

> So with even small "n" the concern is precision. Not speed

So, if https://github.com/sithmel/iter-tools/issues/113 is implemented, this would be relevant, right?

**Comment by sithmel** [comment]
I can consider "size()" :-D

There is also another factor though. It is unlikely that any of the combinatory function will be able to generate that number of items.

**Comment by sithmel** [comment]
I have unintentionally pushed the change directly to master https://github.com/sithmel/iter-tools/commit/6494104af17519ed7af5b4db6b0d68d1f4bf558c

**Comment by KSXGitHub** [comment]
> I have unintentionally pushed the change directly to master [6494104](https://github.com/sithmel/iter-tools/commit/6494104af17519ed7af5b4db6b0d68d1f4bf558c)

One way to avoid this in the future is to create a fork in a new organization and set `remote origin` to that new fork.
