### ISSUE TITLE
Suggestion: partition functions

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#116]
### `partition`

Takes a function and an iterable, returns a pair of 2 iterables.

```javascript
// usage
const [evens, odds] = partition(
  n => n  % 2 === 0, // func: (x: T) => boolean
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] // iterable: Iterable<T>
)

// result
expect(Array.from(evens)).toEqual([0, 2, 4, 6, 8])
expect(Array.from(odds)).toEqual([1, 3, 5, 7, 9])
```

### `multiPartition`

Takes a function and an iterable, returns an array of iterables.

```javascript
// usage
const [a, b, c] = multiPartition(
  x => x % 3, // func: (x: T) => number
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] // iterable: Iterable<T>
)

// result
expect(Array.from(a)).toEqual([0, 3, 6, 9])
expect(Array.from(b)).toEqual([1, 4, 7])
expect(Array.from(c)).toEqual([2, 5, 8])
```

**Comment by sithmel** [comment]
### `partition`
It can be implemented with:
```js
const [iter1, iter2] = tee(iterable)
filter(isEven, iter1)
filter(isOdd, iter2)
```
But I like the idea to create a shortcut, because I think is a very common case.

### `multiPartition`
It is a more rare case, so I would leave users to implement that themselves.

**Comment by KSXGitHub** [comment]
> ### `partition`
> It can be implemented with:
> 
> ```js
> const [iter1, iter2] = tee(iterable)
> filter(isEven, iter1)
> filter(isOdd, iter2)
> ```
> 
> But I like the idea to create a shortcut, because I think is a very common case.

The reason I suggest this is performance, more specifically, I don't want to execute `isOdd`/`isEven` twice.

This `partition` function should not call its `func` callback twice, it is supposed to execute `func` once and choose an iterable to place the item.

Now, compare this:

```javascript
const iterable = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
const evens = []
const odds = []

for (const item of iterable) {
  if (item % 2 === 0) { // `func` is executed just once
    evens.push(item)
  } else {
    odds.push(item)
  }
}

// loop once
// `func` is called once for each item
```

to this:

```javascript
const iterable = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
const evens = []
const odds = []

for (const item of iterable) { // first loop
  if (item % 2 === 0) { // call `func`
    evens.push(item)
  }
}

for (const item of iterable) { // first loop
  if (item % 2 !== 0) { // call `func`
    odds.push(item)
  }
}

// loop twice
// `func` is called twice for each item
```

**Comment by KSXGitHub** [comment]
> ### `multiPartition`
> It is a more rare case, so I would leave users to implement that themselves.

I can implement this, but I don't really want to create a whole new package just for this one function.

**Comment by sithmel** [comment]
I understand your comment about running 2 cycles.
It can be implemented to be similar to ```tee``` and working on a single cycle.

**Comment by KSXGitHub** [comment]
@sithmel 

So, regarding `multiPartition`, I find 3 ways to implement this:
  * Return an array of iterable
  * Return an object
  * Return a Map

Now, I have a few questions:
  1. You wished to leave users to implement this themselves, but in the making of https://github.com/sithmel/iter-tools/pull/118, I saw that implement this kind of function is unusual and quite complicated as implementer has to know es6 iterator's inner working in great details, and thus more likely to cause bugs. That is why I prefer a more centralized approach and like to place the function here, what do you think?
  2. If you agreed that the function belongs here, what should this function creates? (array, object or Map)

**Comment by sithmel** [comment]
I am unable to figure out how ```multiPartition``` can know in advance how many iterable will return.

> You wished to leave users to implement this themselves

Implementing a super generic and reusable ```multiPartition``` might be challenging. I am sure if you need something similar you can cut some corner and write just what you are going to need.

**Comment by KSXGitHub** [comment]
> I am unable to figure out how `multiPartition` can know in advance how many iterable will return.

There're 2 approaches I can think of:
  1. User must specify how many (number of items for an array, or collection of keys for Map/object)
  2. Proxy

**Comment by KSXGitHub** [comment]
Now, regarding Map, one of the reason `multiPartition` would be useful is that it would work well with destructuring, Map does not allow destructuring as far as I know, so there's only 2 options.

**Comment by KSXGitHub** [comment]
> I have no idea how the proxy will behave if you try destructuring it. But I guess it won't work

It works, I just tested it. My only concern is es5.

**Comment by KSXGitHub** [comment]
So I've been thinking about `multiPartition`, looked at the pros and cons of each approach:

## Returning an array of iterables

### Pros

* Allows destructuring

### Cons

* User has to specify number of iterables ahead of time
* Array indices (numbers) are not as meaningful as object keys (labels)

## Returning an object of iterables

### Pros

* Allows destructuring
* Object keys are meaningful

### Cons

* User has to specify keys ahead of time

## Returning a [custom map](https://www.npmjs.com/package/advanced-map-initialized) of iterables

### Pros

* Map keys are meaningful
* User doesn't have to specify keys ahead of time as any key will create an iterable

### Cons

* Does not allow destructuring

## Returning a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

### Pros

* Allows destructuring
* Object keys are meaningful
* User doesn't have to specify keys ahead of time

### Cons

* Does not support ES5 and is impossible to polyfill

## Returning an iterable of iterables

### Pros

* Allows destructuring
* User doesn't have to specify number of iterables ahead of time

### Cons

* Iterable position (equivalent of array indices) are not as meaningful as object keys

---

@sithmel What do you think about this?

**Comment by KSXGitHub** [comment]
I don't intend to use mere arrays/objects as it requires user to specify (number of) keys ahead of time, but I wrote it down to make a clearer picture.

If you prefer the array approach, I would choose **iterable of iterables**, which is basically lazy version of array.



> I propose you an alternative approach:
> 
> ```js
> const [group1, group2, group3] = multipartition([isGroup2, isGroup2, isGroup3], iterable)
> ```

I did think about this, but I think the iterables-of-iterable approach is superior: Write only one function that executes once, as opposed to multiple function.

**Comment by sithmel** [comment]
can you write how would you call multiPartition ? it is not clear to me

**Comment by KSXGitHub** [comment]
> can you write how would you call multiPartition ? it is not clear to me

```
const groups = multiPartition(x => x % 3, range(10)) // groups: Iterable<IterableIterator<number>>
const [a, b, c] = groups // iterables support destructuring, like array
Array.from(a) // -> [0, 3, 6, 9]
Array.from(b) // -> [1, 4, 7]
Array.from(c) // -> [2, 5, 8]
```

**Comment by KSXGitHub** [comment]
Here's a catch, the iterable-of-iterables in an infinite iterable.

**Comment by KSXGitHub** [comment]
> I propose you an alternative approach:
> 
> ```js
> const [group1, group2, group3] = multipartition([isGroup2, isGroup2, isGroup3], iterable)
> ```

Although I do not plan to implement `multiPartition` this way, I may create another function called `multiFilter` in addition to `multiPartition`.

**Comment by sithmel** [comment]
> ```js
> const groups = multiPartition(x => x % 3, range(10)) // groups: Iterable<IterableIterator<number>>
> const [a, b, c] = groups // iterables support destructuring, like array
>```

I don't understand how you know all possible outputs of the function ```x => x % 3``` without having already consumed the iterable ```range(10)```.

**Comment by KSXGitHub** [comment]
> I don't understand how you know all possible outputs of the function `x => x % 3` without having already consumed the iterable `range(10)`.

I don't have to know it ahead of time, `groups` is an infinite iterable that yields "empty" iterables. I also planned to use my very own Map-like class called [`AdvancedMapInitialized`](https://www.npmjs.com/package/advanced-map-initialized).

`AdvancedMapInitialized` is like native `Map`, except when calling `get()`, it doesn't return `undefined` for a key that doesn't exist, instead, it creates a value.

**Comment by KSXGitHub** [comment]
Anyway, if you still don't understand, I will write a prototype tomorrow and you'd have an idea what it looks like 🙂.

**Comment by KSXGitHub** [comment]
@sithmel Since commit https://github.com/sithmel/iter-tools/commit/772a0b43b6b4d1af7200a30cff277e802258e2b7 includes "Fixes ..." in it, I'm assuming GitHub closed this automatically, and since we are not done yet, I'm going to reopen this.

**Comment by sithmel** [comment]
@KSXGitHub I am changing a couple of minor things to partition. You might want to wait before start working on the async version

**Comment by KSXGitHub** [comment]
@sithmel I'll wait. But I think you should make a pull request so we may discuss.

**Comment by sithmel** [comment]
My changes on partition are here #125

**Comment by conartist6** [comment]
Sorry I've been away, I have a full time job and putting all the energy I have left for coding into Sequins.

**Comment by sithmel** [comment]
@KSXGitHub still catching up with this. Now that you showed me https://github.com/sithmel/iter-tools/pull/127 the implementation is clear. I didn't realise you could do that. Cool :+1: 

I am still thinking if this use case is common enough to deserve a function. And in case which one

**Comment by sithmel** [comment]
@conartist6 no need to justify. Happy you took the time to chime in.

**Comment by KSXGitHub** [comment]
> I am still thinking if this use case is common enough to deserve a function. And in case which one

Not as common as `partition`, but yes, it does, at least in my code (I can't recall which one) where I called `ramda.partition` twice.

**Comment by sithmel** [comment]
I had a long thought about multiPartition.

I like the implementation and I think it can be useful but the name and the interface are just not memorable enough. Also I am convinced that using ```tee``` and ```filter``` is just as good in most cases.

In the test you have an example when you are able to decide in which bucket to put an item with a single operation:
```js
const [a, b, c, d] = multiPartition( x => x % 4, range(16))
```
I think that the most common case would be instead:
```js
const [a, b, c, d] = multiPartition( x => {
  if (x === something) return 0
  if (x === somethingElse) return 1
  if (x === somethingOther) return 1
  if (x === somethingEtc) return 1
}, iterable)
```
That is equivalent to:
```js
const [i1, i2, i3, i4] = tee(4, iterable)
const a = filter((x) => x === something, i1)
const b = filter((x) => x === somethingElse, i1)
const c = filter(() => x === somethingOther, i1)
const d = filter(() => x === somethingEtc, i1)
```

**Comment by KSXGitHub** [comment]
> I think that the most common case would be similar to this instead:
> 
> ```js
> const [a, b, c, d] = multiPartition( x => {
>   if (x === something) return 0
>   if (x === somethingElse) return 1
>   if (x === somethingOther) return 1
>   if (x === somethingEtc) return 1
> }, iterable)
> ```

In TypeScript, there're many situations where `multiPartition` is necessary.

One of which is "group by enum":

```typescript
enum Type {
  Foo = 0,
  Bar = 1
}

interface Item {
  readonly type: Type
}

declare const items: Iterable<Item>

const [fooItems, barItems] = partition(item => item.type, items)
```

Of course, enum is a TypeScript specific things, but that doesn't mean pure JavaScript can't apply the same shortcut:

```javascript
const typename2index = { foo: 0, bar: 1 }
const [fooItems, barItems = partition(item => typename2index[item.typename], items)
```

**Comment by KSXGitHub** [comment]
> That is equivalent to:
> 
> ```js
> const [i1, i2, i3, i4] = tee(iterable, 4)
> const a = filter((x) => x === something, i1)
> const b = filter((x) => x === somethingElse, i2)
> const c = filter((x) => x === somethingOther, i3)
> const d = filter((x) => x === somethingEtc, i4)
> ```

This is the same as `partition()` vs 2x `filter()`, `partition` doesn't call a function twice for each item whilst `filter` does. You accepted `partition`, you might as well accept `multiPartition`. [[reference]](https://github.com/sithmel/iter-tools/issues/116#issuecomment-454084544)

**Comment by sithmel** [comment]
>```js
>const [fooItems, barItems] = partition(item => item.type, items)
>```
I can't see the case where you manage to get the answer in a single instruction as the most frequent.

>Not to mention this alternative uses more variables (i1, i2, i3, i4).
it is true that the alternative is longer, but multiPartition:

* solves a less common case
* it is more faster only for a particular case where is very easy to return the index/key
* the api is more complex and difficult to remember (see all discussions around the return value)

>. You accepted partition, you might as well accept multiPartition
One doesn't imply the other

**Comment by sithmel** [comment]
@conartist6 we need a tie breaker here :smile:  I am curious to hear your thought

**Comment by KSXGitHub** [comment]
@sithmel I just realized I used `partition` in place of what should be `multiPartition`, so I edited our comments.

**Comment by sithmel** [comment]
We might want to pick this one back after we finish the work around fork/tee #151 #156

**Comment by sithmel** [comment]
We are currently introducing many functions returning multiple iterables (partition, fork, splitAt etc.) and others that allow to combine multiple iterables in different ways (zip, merge, collate etc.). I can see these different abstractions to fit very well together.

Because of this reason if I had to chose a flavour of multipartition I would chose the one returning an iterable.

@KSXGitHub are you still interested in this ? @conartist6 any views on this ?

**Comment by KSXGitHub** [comment]
Of course, I'm still interested in this

**Comment by KSXGitHub** [comment]
Anyway, this is my (re)implementation of `multiPartition`.

```javascript
import { Exchange } from './internal/queues'
import { iterableCurry } from './internal/iterable'
import AdvancedMapInitialized from 'advanced-map-initialized'

function multiPartition (func, iter) {
  const exchange = new Exchange()
  const queues = new AdvancedMapInitialized(Map, () => exchange.spawnConsumer())
  const iterator = iter[Symbol.iterator]()

  function * part (queueId) {
    while (true) {
      while (!queues.get(queueId).isEmpty()) {
        yield queues.get(queueId).shift()
      }

      const { value, done } = iterator.next()
      if (done) break

      queues.get(func(value)).push(value)
    }
  }

  function * allParts () {
    let queueId = 0
    try {
      while (true) {
        yield part(queueId)
        queueId += 1
      }
    } finally {
      exchange.noMoreConsumers()
      if (typeof iterator.return === 'function') {
        iterator.return()
      }
    }
  }

  return allParts()
}

export default iterableCurry(multiPartition)
```

I want to know if there's anything that needs to be done before writing test cases.

**Comment by sithmel** [comment]
From a very superficial review, I don't think AdvancedMapInitialized is necessary (I have also seen an implementation without it, on one of the many iterations).

**Comment by KSXGitHub** [comment]
> I have also seen an implementation without it, on one of the many iterations

Are you referring to `fork`?

`fork` is a function that only needs one cache, but `multiPartition` need multiple caches, a cache for each value that `func` emits and we do not know which values.

I do not use the map to store resulting iterables, I use it to store caches.

Let me know if I'm mistaken.

**Comment by sithmel** [comment]
I have written a multipartition function that has been factored out "partition" and passes the tests.
```js
import { Queue, fakeQueue } from './internal/queues'
import { iterableCurry } from './internal/iterable'

function * multiPartition (func, iter) {
  const queues = []
  const iterator = iter[Symbol.iterator]()
  let queuesCompleted = false
  let exhausted = 0

  function * part (queueId) {
    if (queuesCompleted === false) throw new Error('You need to finish getting all iterables before start consuming the partitions')
    try {
      while (true) {
        while (!queues[queueId].isEmpty()) {
          yield queues[queueId].shift()
        }

        const { value, done } = iterator.next()
        if (done) break

        const chosen = func(value)
        if (chosen < queues.length) { // throw away item if queue doesn't exist
          queues[chosen].push(value)
        }
      }
    } finally {
      queues[queueId] = fakeQueue // /dev/null
      exhausted++
      if (exhausted === queues.length) {
        if (typeof iterator.return === 'function') iterator.return()
      }
    }
  }

  try {
    while (true) {
      queues.push(new Queue())
      yield part(queues.length - 1)
    }
  } finally {
    queuesCompleted = true
  }
}

function partition (func, iter) {
  const [first, second] = multiPartition((item) => func(item) ? 0 : 1, iter)
  return [first, second]
}

export default iterableCurry(partition)
```
It has an interesting shortcoming: you need to know how many partition you created in advance, before start consuming them and I am firing an exception if you attempt to consume these before (Note: maybe we should do the same for fork).

The reason is: memory efficiency. If I don't know in advance how many iterable I am going to consume, I don't know if I really need to save the item in any queue.
For this reason you can't use this function like this:
```js
for (const part in multipartition(getIndex, iterable)) {
  for (const item in part) { // error
  }
}
```
But this works fine:
```js
const [part1, part2, part3] = multipartition(getIndex, iterable)
for (const item in part1) {
  // ...
}

```

**Comment by KSXGitHub** [comment]
Correctness > efficiency of any kind.

**Comment by sithmel** [comment]
> Correctness > efficiency of any kind.

The solution is correct and efficient. You have to limit the number of queues or you will be unable to close the original iterable. See implementation above where I run:
```js
    } finally {
      queues[queueId] = fakeQueue // /dev/null
      exhausted++
      if (exhausted === queues.length) {
        if (typeof iterator.return === 'function') iterator.return()
      }
    }
```

**Comment by KSXGitHub** [comment]
@sithme

Firstly, https://github.com/sithmel/iter-tools/issues/198#issuecomment-463571943l 

Secondly, you "throw away item if queue doesn't exist", this would invalidate most of my use case, for example (taken from [the original comment](https://github.com/sithmel/iter-tools/issues/116#issue-398901477)):

```javascript
// usage
const [a, b, c] = multiPartition(
  x => x % 3, // this function is going to take 2 first and return 1, which is greater than 0 (queues.length)
  [2, 1, 5, 3, 4, 6, 8, 9, 7, 0] // unlike the original, this array is not sorted
)

// expected result
expect(Array.from(a)).toEqual([3, 6, 9, 0]) // PASS
expect(Array.from(b)).toEqual([1, 4, 7]) // FAIL: received [4, 7], 1 was thrown away
expect(Array.from(c)).toEqual([2, 5, 8]) // FAIL: received [8], 2 and 5 were thrown away
```

And finally, a minor nitpick: You should've used `if (!queuesCompleted)` instead of `if (queuesCompleted === false)`.

**Comment by sithmel** [comment]
@KSXGitHub did you test that ^^^ ?
I think it should work. And if it doesn't it should be an implementation issue, not a logic one

**Comment by sithmel** [comment]
Once you run this:
```js
const [a, b, c] = multiPartition(
  x => x % 3, // this function is going to take 2 first and return 2 (2 % 3), which is greater than 0 (queues.length)
  [2, 1, 5, 3, 4, 6, 8, 9, 7, 0] // unlike the original, this array is not sorted
)
```
We have 3 queues corresponding to 3 iterables: a, b and c.

**Comment by KSXGitHub** [comment]
@sithmel Upon further examination, I think your implementation is fine as long as user does not consume the container iterable lazily (BTW, your implementation is pretty clever actually).

That being said, this would invalidate use cases where user consumes the iterables one by one (which you already foresaw). [[more]](https://github.com/sithmel/iter-tools/issues/198#issuecomment-463636256)

**Comment by sithmel** [comment]
Given that we see a valid use case consuming iterables one by one. I am going to adjust the code accordingly and publish a PR (I am probably going to steal your unit tests @KSXGitHub )

**Comment by KSXGitHub** [comment]
@sithmel You are going to need something likes `AdvancedMapInitialized` in some shape or form. Now looking back, I see that `AdvancedMapInitialized` is pretty bloated (we only need `get` method, we don't need `set`).

You can implement your own "cache maker":

```javascript
function createCacheMaker (init) {
  const allCaches = Object.create(null) // should be clear of any property

  return key => {
    if (key in allCaches) return allCaches[key]

    const cache = init()
    allCaches[key] = cache
    return cache
  }
}
```

Or, if you don't want to reinvent the wheel, you can use [cached-expression](https://www.npmjs.com/package/cached-expression) (another package of mine)

**Comment by sithmel** [comment]
Eventually I used an array, because I can easily dispose the unused queues #199.

I also wanted to check the impact of using fork and multipartition for the same task (see benchmark in the PR).
Fork uses a single queue and is conservative when reading the original iterable.
MultiPartition uses multiple queues and it is eager: it reads and buffer things that might never be used.

My benchmark shows that multiPartition performs better (when partitioning):
```
  fork vs multipartition
    ✓  Fork 10000 items x 258 ops/sec ±1.26% (86 runs sampled)
    ✓  multipartition 10000 items x 568 ops/sec ±0.82% (87 runs sampled)

    Result: multipartition 10000 items is 120.08% faster than Fork 10000 items.
```

On a personal note, I'll be away for a week, so I am going to resume working on iter-tools when I am back

**Comment by sithmel** [comment]
merged
