### ISSUE TITLE
Suggestion: take() and drop()

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#126]
I was quite surprised that iter-tools doesn't have `take()` despite having `takeWhile()`.

Anyway, I want an iterator that yields n first elements and stop:

```javascript
const endless = range() // infinite iterable
const first3 = take(3, endless) // 0, 1, 2
```

**Comment by sithmel** [comment]
[Slice](https://github.com/sithmel/iter-tools#slice) does that

**Comment by KSXGitHub** [comment]
Yeah, I just figured it out just now 😄
