### ISSUE TITLE
Suggestion: Optional multiPartitionProxy()

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#128]
In https://github.com/sithmel/iter-tools/issues/116#issuecomment-455142202, I suggested:

> ## Returning a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)
> ### Pros
> * Allows destructuring
> * Object keys are meaningful
> * User doesn't have to specify keys ahead of time
> 
> ### Cons
> * Does not support ES5 and is impossible to polyfill

Although I did not choose this for `multiPartition` as it requires `Proxy` — a feature that cannot be supported by ES5. I still want to get all the "pros" it offers, so I want to create a `multiPartitionProxy` that will act depends on the presence of `(global).Proxy`:
  * If `Proxy` is present, it does what it's meant to do.
  * If `Proxy` is missing, it throws an error.

@sithmel What do you think?

**Comment by sithmel** [comment]
We are currently adding many features to work with iterables of iterables. See #151 
I would shelve this for now. Is that ok @KSXGitHub ?
