### ISSUE TITLE
Suggestion: function that split iterable into two at a given position

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#134]
## Split by Index

```javascript
function splitAt (position, iter) {
  const [first, second] = tee(iter)
  return [
    slice({ end: position }, first),
    slice({ start: position }, second)
  ]
}
```

## Split by Condition

...

**Comment by conartist6** [comment]
See my comments on https://github.com/sithmel/iter-tools/pull/135, I think they would also apply to this function.

**Comment by conartist6** [comment]
We shouldn't be helping people do things with iterables that they shouldn't be using iterables to do.

**Comment by KSXGitHub** [comment]
@conartist6 But won't be as performant

**Comment by sithmel** [comment]
I would move the discussion to #136 that seems to be fulfilling the same goal

**Comment by KSXGitHub** [comment]
> I would move the discussion to #136 that seems to be fulfilling the same goal

You're definitely right.

**Comment by KSXGitHub** [comment]
Reopen as https://github.com/sithmel/iter-tools/issues/136#issuecomment-455817799 arises.

**Comment by conartist6** [comment]
Yeah having had these discussions I like your `splitAt` proposal better now.

**Comment by sithmel** [comment]
This is blocked until *fork* is ready #151

**Comment by sithmel** [comment]
fork is now on master @KSXGitHub 

I like both splitAt and splitBy ideas ;-)
