### ISSUE TITLE
Suggestion: pipe() — like pipeline(), but does not return a function

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#137]
## Why?

Since `pipeline` is just a reverse `compose`, I must use 2 pairs of parentheses (2 function calls) every time I use `pipeline`. That's not only makes the code looks ugly, it's also annoying.

## Suggestion

Create a `pipe` function that unlike `pipeline`, it takes 1 value and many functions and returns a value.

```javascript
const result = pipe(
  range(),
  filter(x => x % 2 === 0),
  map(x => x % 3)
)
```

**Comment by sithmel** [comment]
You can do that:
```js
const result = pipeline(
  () => range(),
  filter(x => x % 2 === 0),
  map(x => x % 3)
)
```

**Comment by KSXGitHub** [comment]
@sithmel You missed the point: `result` in your example is a function whilst in mine, it is an iterable.

So your example should rather be:

```javascript
const result = pipeline(
  () => range(),
  filter(x => x % 2 === 0),
  map(x => x % 3)
)() // ← extra pair of parentheses
```

**Comment by sithmel** [comment]
my bad. let's fix pipeline instead!

**Comment by KSXGitHub** [comment]
BTW, The implementation of `pipe` is rather simple:

```javascript
function pipe (x, ...fns) {
  return fns.reduce((x, fn) => fn(x), x)
}
```

as opposed to `pipeline`:

```javascript
function pipeline (...fns) {
  return fns.reverse().reduce((f, g) => (...args) => f(g(...args)))
}
```

**Comment by KSXGitHub** [comment]
> my bad. let's fix pipeline instead!

Would that be a breaking change?

**Comment by sithmel** [comment]
nah, I never properly released that.

As a matter of fact it is about time to release a new version

**Comment by KSXGitHub** [comment]
You can use my `pipe` implementation above.

And please don't release before I update its type definition.
