### ISSUE TITLE
Unifying async/sync functions

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#14]
I have realised that:
```js
const it = require('iter-tools')
it.iter(function * () {})[Symbol.iterator]
it.asyncIter(async function * () {})[Symbol.asyncIterator]
```
is a quick way to find out if an iterable is sync or async.

At this point I could potentially merge all sync/async functions. I could check the iterable in input and run the appropriate implementation.

I can also implement in the same way "toArray" (working for sync/async iterables) and "consume" to use as an alternative of the for construct:
```js
consume(func, iterable)
// equivalent to:
for (const v of iterable) {
  func(v)
}
// or:
for await (const v of iterable) {
  func(v)
}
```
In this way I can write code that runs transparently on async or sync iterable.

Any thoughts ? @gwpmad @mongolianprincess @conartist6 @kmxz @KSXGitHub

**Comment by conartist6** [comment]
It believe it is possible to define something like this:
```
class Weird {
  *[Symbol.iterator] () {
    yield 42;
  }
  async *[Symbol.asyncIterator] () {
    yield Promise.resolve(42);
  }
}
```

Which iteration is the default in that case? Is there a way to override which one gets picked? Can you think of a reasonable circumstance in which someone would write that?

**Comment by sithmel** [comment]
@conartist6  That's the only objection I could think of, too.
It is a corner case though, not sure if that could happen in the real world

**Comment by conartist6** [comment]
I think it might be fine. If both exist, prefer the async one. Create an iterSync helper.

It should just proxy to Symbol.iterator, throwing an error if it is not present.

I do think the use case for having both may be legit. Let's say you're proxying an iterable of Promises and wanted to offer APIs to allow running them both in sequence and in parallel. You offer them in sequence as an async iterator. Parallel consumers will just put the result into Promise.all(). For them usage now looks like: ```Promise.all(iterSync(myDualIterable));```

**Comment by KSXGitHub** [comment]
I don't think it is possible to achieve. On one hand, we have async returns promise in synchronous context making for-loop in synchronous context impossible. On the other hand, it is possible to iterate through sync iterable in sync and async alike but it is synchronous - not what we want when using async iterate.
