### ISSUE TITLE
Move 'Function guidelines' from wiki to CONTRIBUTING.md

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#143]
Contributors usually don't expect contribution guides to be in wiki page. On the other hand a `CONTRIBUTING.md` is hard to ignore.

ref: https://github.com/sithmel/iter-tools/wiki/Function-guidelines

**Comment by sithmel** [comment]
contribution guide is long due. I'll take care of it

**Comment by sithmel** [comment]
added in #147

**Comment by sithmel** [comment]
done
