### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#144]
https://github.com/sithmel/iter-tools/blob/ca800a916082272b437022fe1cc11fae4bc95a35/src/async-tee.mjs#L43

At line 43 of `async-tee.mjs`, it calls `iterator.return()`, but in this context, `iterator.return` might be async (returning a `Promise`). I find it strange that there's no `await` before `iterator.return()`.

**Comment by conartist6** [comment]
Hmm, ok. I'm looking at [the spec](https://github.com/tc39/proposal-async-iteration#async-generator-functions) and it does appear to say that return may be a promise. I mean, it cou
