### ISSUE TITLE
Recurring code pattern #1: currying

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#149]
In almost every module, I see this pattern:

```javascript
function functionName (func, iter) { ... }

export default function curriedFunctionName (func, iter) {
  if (typeof iter === 'undefined') {
    return iter => functionName(iter)
  }
  return functionName (func, iter)
}
```

These patterns can be eliminated by using a `curry` wrapper:

```javascript
// src/internal/curry.mjs

export default function curry (func, length) {
  const curried = (...args) => args.length < length
    ? (...suffix) => curried(...args, ...suffix)
    : func(...args)
  return curried
}
```

```javascript
// src/function-name.mjs

import curry from './internal/curry'

function functionName (func, iter) { ... }

export default curry(functionName, 2)
```

I also saw that some test suites test currying support of their test subjects. A `curry` wrapper should eliminate the needs of writing those tests over and over again by replacing them all with 1 single test suite that tests `curry()` itself.

**Comment by sithmel** [comment]
Completely positive with this.

**Comment by sithmel** [comment]
A couple of notes:
* some function has variable args in the curried version. That logic needs to be moved into the original function [here for example](https://github.com/sithmel/iter-tools/blob/master/src/async-map.mjs)
* it is possible to give to the output function a meaningful name. [This is battle tested for that task](https://github.com/sithmel/async-deco/blob/master/src/utils/func-renamer.mjs)

**Comment by KSXGitHub** [comment]
Now I wish to that you guy created a `parallelAsyncMap` instead of adding `concurrency` directly to `asyncMap`. But what's done cannot be undone.

**Comment by KSXGitHub** [comment]
@sithmel Aside from `asyncMap` and `asyncFilter`, how many more functions do you think can be upgraded to handle concurrency? Maybe it's worth creating a specialized function to handle this.

**Comment by sithmel** [comment]
> how many more functions do you think can be upgraded to handle concurrency?

I don't think there are others.

> Maybe it's worth creating a specialized function to handle this.

These are not about calling the input iterable in parallel (we have asyncBuffer for that). These are about calling the input function in parallel. I don't think you can abstract that in a specialised function

**Comment by KSXGitHub** [comment]
> > how many more functions do you think can be upgraded to handle concurrency?
> 
> I don't think there are others.

I think as long as the input function calls are independent to each other, it is possible to call input functions concurrently.

> These are not about calling the input iterable in parallel (we have asyncBuffer for that). These are about calling the input function in parallel.

I never has this confusion in the first place.

> I don't think you can abstract that in a specialised function

Guess what you said when I create `multiPartition`? Anyway, I didn't try it, I can't say whether it is possible nor impossible.

**Comment by KSXGitHub** [comment]
> I don't think there are others.

I think as long as the input function calls are independent to each other, it is possible to add concurrency.



> These are not about calling the input iterable in parallel (we have asyncBuffer for that). These are about calling the input function in parallel.

I never has to confusion in the first place.

> I don't think you can abstract that in a specialised function

Guess what you said when I make `multiPartition`! Anyway, I can't say if it is possible or impossible until I try.

_(Previous comment was deleted by mistake, this comment is just the previous one)_

**Comment by sithmel** [comment]
I am definitely convinced that a proper curry function is necessary.

Are you going to work on it @KSXGitHub ?

I can pick this up otherwise ...

**Comment by KSXGitHub** [comment]
> Are you going to work on it @KSXGitHub ?

Implementing a `curry` is relatively quick, but refactor the whole codebase to use the new `curry` function is repetitive, time-consuming, and boring. I prefer not to.

**Comment by conartist6** [comment]
There are a few that should stay how they are. `reduce` for sure.

**Comment by sithmel** [comment]
Changes in #157
