### ISSUE TITLE
functions to use in a pipeline

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#151]
In this ticket, I'd like to discuss 2 new functions and a couple of changes. But before, let me explain the context.
Last summer I've experimented with data pipelines, using async-iterables instead of streams. Using data pipelines you have often the necessity to fork the iterable and to apply different sub-pipelines to the forked ones. Here's an example:
```js
...
const [copy1, copy2] = asyncTee(iterable, 2)
const transformed1 = aPipeline(copy1)
const transformed2 = anotherPipeline(copy2)
const merged = asyncMerge(asyncMergeByReadiness, [transformed1, transformed2])
for await (const item of merged) {
  // ...
}
```
I'd like the previous code to be simpler. So here's a list of proposal:

## 1 - merge - asyncMerge default function
merge - asyncMerge currently requires a function to decide what item consume first. Adding a sensible default can simplify most common cases. I propose to use a round robin algorithm on merge and asyncMergeByReadiness on asyncMerge.

## 2 - fork: a better tee
tee api come directly from the [Python itertools](https://docs.python.org/2/library/itertools.html#itertools.tee). It would be very convenient having a curriable version. Even better if it returns a iterable like @KSXGitHub did on the [multiPartition](https://github.com/sithmel/iter-tools/issues/116#issuecomment-455700232), so we don't need to specify the number of iterables returned. Something like:
```js
const [copy1, copy2] = asyncFork(iterable)
// equivalent to
const [copy1, copy2] = asyncTee(iterable, 2)
```

## 3 - apply multiple pipelines to an array of iterables
I could not come up with a good name yet. Let's call this function pipeMultiple for now.
```js
const [transformed1, transformed2] = pipeMultiple([aPipeline, anotherPipeline], [copy1, copy2])
// equivalent to
const transformed1 = aPipeline(copy1)
const transformed2 = anotherPipeline(copy2)
```
It should also be curriable.

## the result
```js
...
const merged = pipe(
  asyncFork(),
  pipeMultiple([aPipeline, anotherPipeline]),
  asyncMerge()
)

for await (const item of merged) {
  // ...
}
```

**Comment by KSXGitHub** [comment]
> ## 2 - fork: a better tee
> tee api come directly from the [Python itertools](https://docs.python.org/2/library/itertools.html#itertools.tee). It would be very convenient having a curriable version. Even better if it returns a iterable like @KSXGitHub did on the [multiPartition](https://github.com/sithmel/iter-tools/issues/116#issuecomment-455700232), so we don't need to specify the number of iterables returned. Something like:
> 
> ```js
> const [copy1, copy2] = asyncFork(iterable)
> // equivalent to
> const [copy1, copy2] = asyncTee(iterable, 2)
> ```

So `asyncFork` is basically `asyncTee` with `n = Infinity`? What about the sync version (`fork`)?

**Comment by KSXGitHub** [comment]
> ## the result
> ```js
> ...
> const merged = pipe(
>   asyncFork(),
>   pipeMultiple([aPipeline, anotherPipeline]),
>   asyncMerge()
> )
> 
> for await (const item of merged) {
>   // ...
> }
> ```

You think you meant this:

```diff
 const merged = pipe(
+  iterable,
-  asyncFork(),
+  asyncFork,
   pipeMultiple([aPipeline, anotherPipeline]),
-  asyncMerge()
+  asyncMerge
 )
```

**Comment by sithmel** [comment]
I meant this (asyncMerge is curried with a default argument):
```
...
const merged = pipe(
  iterable,
  asyncFork,
  pipeMultiple([aPipeline, anotherPipeline]),
  asyncMerge()
)

for await (const item of merged) {
  // ...
}
```

**Comment by sithmel** [comment]
> Anyway, I think this is doable. We just need to copy and change multiPartition a little.

Exactly :smile:

**Comment by KSXGitHub** [comment]
Wait, the name of the function is `pipeline`, but I think it still makes sense to create a `pipe` alias (just like you did with `chain`/`concat`)

**Comment by conartist6** [comment]
@sithmel I see this is where the suggestion for `fork` came from and (consulting the python docs) the core of its implementation. I suggested on @KSXGitHub's diff that we just have a single tee function, whose default fork count is Infinity instead of 2. I guess I can sort of see why it might be good not to touch the tee default of 2 -- particularly because the name, tee, implies two already.

Wait, I've got it, we can call the new function `infiniTee`! XD

**Comment by sithmel** [comment]
After having a look at @KSXGitHub experiments #153 #155 I realised that I am happy with a curriable tee.
The current tee has the arguments in the wrong order (iterable, number), we can:
- fix *tee* in a major release
- create *fork* (basically a curriable tee) and deprecate *tee*

**Comment by conartist6** [comment]
so in the future, to confirm, there would be no `tee` and `fork` usages would look like:
`fork(iterable) // infinite copies, full array buffer`
`fork(2, iterable) // two copies, partial dequeue buffer`
`fork(2)(iterable) // ditto`

I'd be ok with that.

**Comment by sithmel** [comment]
> ```fork(iterable) // infinite copies, full array buffer```

I am not sure this can be sorted out (waiting someone to prove me wrong though :-) )

**Comment by sithmel** [comment]
I am persuaded that it would be easier building pipelines if tee/fork returns an array instead of an infinite iterable.
see the idea here: #158

**Comment by sithmel** [comment]
Based on this description here: https://github.com/sithmel/iter-tools/pull/155#issuecomment-457497773 (thanks @conartist6 ) fork returning infinite copies looks doable.

I don't get why this requires a ```full array buffer``` @conartist6 
This should be implemented like you describe here https://github.com/sithmel/iter-tools/issues/156

**Comment by sithmel** [comment]
> I don't get why this requires a full array buffer @conartist6

I get it why. You can't be sure there won't be another forkedIterable. But actually you can check if the iterable returned by *fork* has been consumed (method return called), then you are free to get rid of the old items.

**Comment by sithmel** [comment]
I'll try to solve this for good building an abstraction on top of deque to fix  #156

**Comment by conartist6** [comment]
@sithmel You're quite right, I plan next to expand my implementation to be able to do that.

**Comment by sithmel** [comment]
there are already other tickets covering what is missing here: #158 #169
