### ISSUE TITLE
Suggestion: pick(), omit()

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#154]
### `pick()`

It takes a set of keys and an object and returns an object with only selected keys

```haskell
pick :: Iterable keys ->  Object dict -> Object
```

**Example:**

```javascript
// expect: { foo: 123 }
const result = pick(['foo', 'bar'], { foo: 123, baz: 456 })
```

### `omit()`

It takes a set of keys and an object and returns an object without selected keys

```haskell
omit :: Iterable keys ->  Object dict -> Object
```

**Example:**

```javascript
// expect: { baz: 456 }
const result = omit(['foo', 'bar'], { foo: 123, baz: 456 })
```

### Others

* `mapPick()`, `mapOmit()`
* async versions that work on promise? **[discuss]**
* support computational "keys"? **[discuss]**

### SQL's `select from`-esque syntax

```javascript
const input = [
  { a: 0, b: 1, c: 2 },
  { a: 3, b: 4, c: 5 },
  { a: 6, b: 7, c: 8 },
  { a: 9 }
]

const result = pipe(
  input,
  map(pick(['a', 'b']))
)
```

**Comment by sithmel** [comment]
I would leave this to other libraries like ramda https://ramdajs.com/docs/#pick

Any reason in particular you would like to see it here @KSXGitHub ?

**Comment by KSXGitHub** [comment]
> I would leave this to other libraries like ramda https://ramdajs.com/docs/#pick

Oh, I forgot, it works just fine
