### ISSUE TITLE
tee should allow its iterators to return early

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#156]
A selling point of tee the way we wrote it is that it will work on infinite iterables -- as long as the consumers keep consuming each iterable resuling from the tee all the old entries are removed from the dequeues and we don't keep much of anything in cache.

But what if one of those consumers stops consuming? Now its cache will begin to fill up -- essentially creating a memory leak.

We should return an iterable with a `return` method, which method cleans up by destroying that iterable's tee cache.

**Comment by conartist6** [comment]
I also think tee should only keep a single dequeue internally, whose size is determined by the consumer lagging farthest behind the current item in the source iterable.

**Comment by sithmel** [comment]
True. this needs to be addressed

**Comment by sithmel** [comment]
partition has the same problem. If a generator function is exhausted, it will still queue items
```js
function partition (func, iter) {
  const satisfied = new Dequeue()
  const unsatisfied = new Dequeue()
  const iterator = ensureIterable(iter)[Symbol.iterator]()
  let exhausted = 0

  function * part (queue) {
    try {
      while (true) {
        while (queue.length) {
          yield queue.shift()
        }

        const { value, done } = iterator.next()
        if (done) break

        const chosen = func(value) ? satisfied : unsatisfied
        chosen.push(value)
      }
    } finally {
      exhausted++
      if (exhausted === 2) {
        if (typeof iterator.return === 'function') iterator.return()
        // replace satisfied or unsatisfied with a fake object that puts items in /dev/null
      }
    }
  }

  return [part(satisfied), part(unsatisfied)]
}
```

**Comment by sithmel** [comment]
this has been fixed with the new fork
