### ISSUE TITLE
mapFunc (temporary name)

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#158]
pipeMulti carries on multiple iterable transformations in parallel:
```js
const iter1 = range(10)
const iter2 = range(10)
const even = filter((n) => n % 2 === 0)
const square = map((n) => n * n)
const [evenIter1, squareIter2] = pipeMulti([even, square], [iter1, iter2])
```
It can be used in pipelines, leveraging fork (or tee)
```js
const [evenIter1, squareIter2] = pipe(
  range(10),
  fork(2), // this fork return 2 items
  pipeMulti([even, square])
)
```
Given that often times you precede pipeMulti with "fork", it would be nice if pipeMulti can fork automatically whenever the second argument is an iterable instead of an array.
```js
const iter = range(10)
const even = filter((n) => n % 2 === 0)
const square = map((n) => n * n)
const [evenIter1, squareIter2] = pipeMulti([even, square], iter)
```
That become:
```js
const [evenIter1, squareIter2] = pipe(
  range(10),
  pipeMulti([even, square]) // it implicitly fork(2)
)
```

**Comment by KSXGitHub** [comment]
> pipeMulti (temporary name)

How about `mapMulti`, `multiMap`, `mapfns`?

**Comment by sithmel** [comment]
```map``` implies that I am mapping (as in map(func, iterable)) but I am doing a different thing here

**Comment by KSXGitHub** [comment]
> ```map``` implies that I am mapping (as in map(func, iterable))

As in `map([func1, func2], iterable)`. `even` and `square` in your example are supposed to be functions, right?

> but I am doing a different thing here

You fork the iterable into multiple copies, and then pass each element to the functions to get results, which is what map does.

**Comment by sithmel** [comment]
I am using ```filter``` in the example. It is like having multiple pipelines

**Comment by KSXGitHub** [comment]
> it would be nice if pipeMulti can fork automatically whenever the second argument is an iterable instead of an array

Array is an iterable, what if I want to use array? I think it's better if you make 2 functions for user to choose instead of 1 attempting to be smart.

**Comment by KSXGitHub** [comment]
> I am using `filter` in the example. It is like having multiple pipelines

My bad, I didn't read it carefully 😄.

**Comment by sithmel** [comment]
> Array is an iterable, what if I want to use array? I think it's better if you make 2 functions for user to choose instead of 1 attempting to be smart.

true :man_facepalming:

**Comment by KSXGitHub** [comment]
This function is like reverse version of `map` (or is it "inverse", "transverse", "converse"? I don't know, I'm not an English expert) whereas `map` applies one function on multiple values, this function applies multiple functions on one value.

This function (I'd call it `fmap` for now) can be implemented using `map`:

```javascript
function fmap (fns, input) {
  return map(func => func(input), fns)
}
```

**Comment by sithmel** [comment]
This will be pretty much the implementation @KSXGitHub :+1: 

I don't think the name should reflect the implementation but rather its use. I'll run the idea with my colleagues (English is not my mother tongue either)
