### ISSUE TITLE
pipe. revert to old behaviour

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#159]
https://github.com/sithmel/iter-tools/issues/137

I regret having done that change.

With this proposal https://github.com/sithmel/iter-tools/issues/158 and #151 we should be able to compose a pipeline like this:
```js
const [evenIter1, squareIter2] = pipe(
  fork(2), // this fork return 2 items
  pipeMulti([even, pipe(square, odd)]) // use pipe to compose
)(range(10))
```

Also I noticed ramda has the old behaviour: https://ramdajs.com/docs/#pipe

**Comment by KSXGitHub** [comment]
if user wants function, they can write function:

```javascript
const f = x => pipe(x, ...)
```

**Comment by KSXGitHub** [comment]
I don't like my code being overly verbose.

**Comment by KSXGitHub** [comment]
For reference, there's a pipeline operator proposal:
  * https://github.com/tc39/proposal-pipeline-operator
  * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator

**Comment by KSXGitHub** [comment]
> ```javascript
>   pipeMulti([even, pipe(square, odd)]) // use pipe to compose
> ```

It's look like reverse version of `compose`, you can name it `rcompose`, or you can reuse `pipeline`.
