### ISSUE TITLE
Currying perf

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#17]
A major perf issue in this library is the implementation of currying. Currying is, in iter-tools, patterned like this:
```
export default function find (func, iterable) {
  function curriedFind (i) {
    // ...
  }
  if (iterable) {
    return curriedFind(iterable)
  }
  return curriedFind
}
```
This is problematic, because every time find is called a new function must be created.

The patterning should be:
```
export default function find (func, iterable) {
  if (!iterable) {
    return iterable => find(func, iterable)
  }
  // ...
}
```
Now in the normal situation, when all the params are passed, we don't have to create a new function.
I'm not certain of all the moving parts in play, but I suspect the current patterning might interfere with precompilation. These curriedMethod functions will get hit a lot, and if they're not all instances of the same function I don't think v8 would be able to detect them getting hot in order to do precompilation.

Also in the proposed style currying is done with an arrow function, which is lighter weight than a normal function due to optimizations of its own (doesn't create arguments, has no prototype).

**Comment by sithmel** [comment]
Very good point!
