### ISSUE TITLE
Test for cleanup on exception

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#171]
Wherever we manually invoke `iterable[Symbol.iterator]()` and pass control flow back to the user with a callback or similar, we should be careful to `return()` the source iterable if the user's code throws an exception.

**Comment by sithmel** [comment]
* fork (close on finally)
* async-fork (close on finally)
* reduce/async-reduce (close on finally)
* group-by/async-group-by (close on finally)
* partition/async-partition (close when both output iterator are returned - using finally)
* zip/zipLongest (close all input iterables on finally)
* merge (it should work bu it will soon drop dead)

Everything looks ok here.
But it is a good idea creating test cases for these (like the one on fork).

I am updating the title of the ticket

**Comment by sithmel** [comment]
This is a great first timer ticket @stecb :-)

**Comment by stecb** [comment]
Hello folks! Will have a look tonight/tomorrow :) probably will need some help at the beginning.

**Comment by sithmel** [comment]
welcome @stecb !
@conartist6 wrote a [great test case](https://github.com/sithmel/iter-tools/blob/master/src/__test__/fork.test.js) to check if we are calling the method "return" on to close an input iterator.
I wrote something about this mechanism in the wiki https://github.com/sithmel/iter-tools/wiki/Generator-functions-work-flow

But ping me if you need anything

**Comment by sithmel** [comment]
* splitAt, asyncSplitAt need tests as well

**Comment by sithmel** [comment]
and multiPartition will soon need that too

**Comment by sithmel** [comment]
Taken care of here: https://github.com/sithmel/iter-tools/commit/19c3aa89e57446ec4e7f3b1d951a4f0af850cf97
