### ISSUE TITLE
Why is asyncFilter calling asyncBatch

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#176]
The call to `asyncBatch` seems to be there in order to provide concurrency, but batch does not provide any concurrency, it just delays the emission of results until more results are ready. This sucks! If you try to consume only a single result from `asyncFilter` with a concurrency higher than 1, it will never return! It'll just sit there waiting for more items to put in its batch! Why would we sacrifice the correctness of the implementation for a perf optimization that we don't even know we need, and clearly don't know how to properly test?

**Comment by sithmel** [comment]
yep, missed that case!

**Comment by conartist6** [comment]
Could you tell me what it means to `asyncFilter` with a concurrency of 2?

**Comment by conartist6** [comment]
Actually while that's better, it's still fatally flawed. It is forced to wait for an item of the source iterable before it can yield a filtered item, which is silly because most of the time I suspect the filtering function itself will be synchronous. It is however the best that you can do while locked into using `for..await` for control flow.

**Comment by sithmel** [comment]
I like this approach. you could leverage Promise.race, when the buffer is full.

In my use case I had a stream of ids and I need to retrieve data from a rest endpoint for every id. So calling these endpoints in parallel gave a great perf boost. (I am talking about asyncMap, but asyncFilter behaves the same)

**Comment by conartist6** [comment]
I have an even better approach that is almost ready to go which should actually be optimal and correct in every case.
