### ISSUE TITLE
deprecate iterable, asyncIterable

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#179]
Their only purpose seems to be converting an object like:
```js
{
  next: ()  => {}
}
```
to an iterable.
I don't think they are particularly useful, given that if you already manage to have that, you can probably add:
```js
{
  next: ()  => {},
  [Symbol.iterator]: function () {
    return this
  }
}
```
Also the name doesn't really tell you what they do.

**Comment by KSXGitHub** [comment]
We can use it for a [different purpose](https://github.com/sithmel/iter-tools/issues/184)

**Comment by sithmel** [comment]
It looks like a footgun to me.

**Comment by conartist6** [comment]
What if we changed the names again, to `fromIterator` and `fromAsyncIterator`. It would mesh with the naming convention we established with `toArray`, which is that `to` implicitly implies that it is an iterable which is being converted to an array.

**Comment by sithmel** [comment]
@conartist6 I question the purpose itself of these 2 functions.

I really can't see a use case for them

**Comment by conartist6** [comment]
I certainly hope that the methods aren't/wouldn't be used much, but it also seems like a pretty elementary operation. The core design of iterables creates two separate concepts. Iterators and iterables are a fundamental part of the system, not just a mistake that will be papered over eventually. Given that anyone who understands how these concepts work together should understand what this function does, I don't think we should probably keep it. We could however clean up the documentation, and more actively direct people to just make their iterators iterables instead using these methods.

**Comment by sithmel** [comment]
Removed them. I added some extra documentation about iterables and iterators
