### ISSUE TITLE
Proposal: Sequences

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#18]
I'm thinking of Immutable.js here.

When native Map and Set support became widespread there wasn't so much point in working with them, because there weren't tools (like iter-tools) to help out.

What I personally did instead, when possible, was just to use Immutable.js data structures and very well rounded standard library. Sometimes though I did actually need a data structure which could be mutated, so I'd use one. Now I had(have) mutable and immutable objects mixed together sometimes, and that sucks because both require different syntaxes to work with.

Iterators are the shared API surface between native Array/Map/Set and Immutable.js List/Map/Set. Both implement .keys, .values, and .entries iterators for all their objects.

I propose to make things even a little simpler. In immutable, Seq is pretty much just an OO wrapper around an iterator. It keeps track of which sort of data it represents (indexed, keyed, or set), a particular iterator instance, and returns a chaining object on which you can call important methods (which in turn also have their results wrapped in Sequences).

I'm thinking of implementing sequences -- I don't think the base functionality should be too hard, at which point it would be substantially easier to operate in environments in which both mutable and immutable data was necessary.

**Comment by sithmel** [comment]
Can you write an example?

**Comment by conartist6** [comment]
A sequence might look like:
`Seq(range(3)).map(x => x+1).filter(x => x > 2).toArray()`
Behind the scenes iterators are being used to prevent storage allocation on intermediate steps.
You can obviously write the same thing in iter-tools already, but it looks like:
`Array.from(filter(x => x > 2, map(x => x+1, range(3))`
Each style on its own is not too hard to read, but needing to read logic expressed in both styles is a total headache.

**Comment by conartist6** [comment]
Also Sequences work much better in the land of pretty-printing, where they can flow downwards without repeated assignments.

**Comment by sithmel** [comment]
I had some thought about having that in the past.
I am not 100% sure this is something for iter-tools or for an external library that depends on iter-tools

**Comment by conartist6** [comment]
Yeah it could be an external library. In particular there's a conflict with iter-tools' pay-only-what-you-need philosophy. Sequences need all the methods to be defined on their chaining prototypes.

My main uncertainty if it doesn't go in this library is what to call it. seq, sequence, and mutable are all taken already : (.

**Comment by conartist6** [comment]
Haha, dunno iter-tools seems like a fine name to me. It describes what the library does perfectly. I think it's interesting that the limited availability of good names has to be one of the driving forces against wanton forking in the ecosystem.

I think maybe "sequins". Brb gotta snap that up.

**Comment by sithmel** [comment]
I had an idea on how to implement this while retaining the pay-only-what-you-need nature of iter-tools.
What if you have to build the library like:
```js
import { map, filter, buildSequence } from 'iter-tools'

export default Sequence = buildSequence({ map, filter })
```
and then
```js
import Sequence from './sequence'
const seq = new Sequence(iterable)

seq.map(..).filter(...)
```
The only additional step is that you have to "assemble"  the library at run time.

**Comment by conartist6** [comment]
It's an interesting thought, but I'm not sold. For one it would be hard to type correctly, and it would be relatively critical that a type system understood the entire construct so that it could warn of issues, like calling a method which wasn't actually defined, or being clever by passing non-iter-tools functions to `buildSequence`.

Secondly I think it's hard to code. One of the big benefits of sequences is that a number of the APIs are context dependent. `map` as a method means something different when run on an indexed sequence (a flat iterable) vs when you run it on a entry sequence (an iterable of `[key, value]` pairs). In that second case it should actually transform `[key, value] => [key, mappedValue]`. The power of Sequences is that they can keep state internally so that they know which map logic was intended. It also means that the user couldn't just feed in a generic `map` function.

If you did want to make Sequence a normal part of iter-tools, it wouldn't incur it's require-the-whole-library costs unless the developer actually imported Sequence. I think then everyone might be reasonably served. The authors of libraries and modules would not use sequences in order to keep their code footprint lightweight. Those creating applications would have a straightforward choice as to whether the increased weight was worth it for the syntax.

**Comment by conartist6** [comment]
By the way, I did settle on `sequins` for this, and I've got a quite a bit of it written. Repo is [here](https://github.com/conartist6/sequins/tree/master/src).

**Comment by sithmel** [comment]
I think this can be close now
