### ISSUE TITLE
asyncFork() does not work (master branch)

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#180]
```
TypeError: (0 , _ensureAsyncIterable.default)(...)[Symbol.iterator] is not a function
  at asyncFork (es2015/async-fork.js:31:20
```

**Comment by sithmel** [comment]
How can I reproduce the problem ? my tests are passing

**Comment by KSXGitHub** [comment]
> my tests are passing

Your tests do not execute `asyncFork`, only `fork`.

https://github.com/sithmel/iter-tools/blob/f9a264e7f02448b3bcb29b3dd20c67b3b9e5e7f7/src/__test__/fork.test.js#L2

**Comment by sithmel** [comment]
:facepalm:

**Comment by KSXGitHub** [comment]
**Suggestion:** Add `--coverage` to your `jest` command to display coverage.

**Comment by sithmel** [comment]
great advice @KSXGitHub 
I noticed that it makes tests super slow.
I am going to add a test:coverage script :+1:

**Comment by sithmel** [comment]
added tests and fixed master

coverage command was always there under my nose ```npm run coverage```
