### ISSUE TITLE
Splitby

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#193]
This would be a function that would split one iterable in two, depending on a condition. 
```js
const [first, second] = splitBy((item) => item === ' ', 'hello world')
Array.from(first) // ['h', 'e', 'l', 'l', 'o']
Array.from(second) // [' ', 'w', 'o', 'r', 'l', 'd']
```
^^^ I am undecided about the separator

It should be an optimised version of:

```js
const [clone1, clone2] = fork('hello world')
const first = takeWhile((item) => item !== ' ', clone1)
const second = dropWhile((item) => item !== ' ', clone2)
```

**Comment by sithmel** [comment]
proposed in #134

**Comment by KSXGitHub** [comment]
The condition function may return `true` multiple times (I know this isn't the case with `takeWhile` and `dropWhile`, but it may be in the optimised version), should we also split the iterable into more than 2 parts?

**Comment by sithmel** [comment]
You are right @KSXGitHub . It is better if I figure out a use case before going on with this

**Comment by conartist6** [comment]
What if we just called it `split` and it removed the sentinel item and emitted a fully variable number of iterables? Then it would be the iterable equivalent of `String.prototype.split`.

**Comment by KSXGitHub** [comment]
> What if we just called it `split` and it removed the sentinel item and emitted a fully variable number of iterables? Then it would be the iterable equivalent of `String.prototype.split`.

`String.prototype.split` does not take function argument.

**Comment by conartist6** [comment]
So... ? I'm not saying we copy the API exactly, I'm just saying we use the basics of how it works.

**Comment by KSXGitHub** [comment]
Regarding https://github.com/sithmel/iter-tools/issues/193#issuecomment-462602728, since `String.prototype.split` can make more than 2 parts, our `split` should also split an iterable every time the function return `true`.

**Comment by KSXGitHub** [comment]
Another thing, in [the example provided by @sithmel](https://github.com/sithmel/iter-tools/issues/193#issue-409012432), I see that `Array.from(second)` has the separator (`' '`) as the first element. This is different from `String.prototype.split` where no substring contains separator.

**Comment by conartist6** [comment]
Yes, that's what I was seeing in the example, and what I was suggesting we change.

**Comment by sithmel** [comment]
I think we are all on the same page now:
```js
const [hello, world] = split((item) => item === ' ', 'hello world')
Array.from(hello) === ['h', 'e', 'l', 'l', 'o']
Array.from(world) === ['w', 'o', 'r', 'l', 'd']
```
and also:
```js
const [first, part] = split((item) => item === ' ', 'first part second part')
Array.from(first) === ['f', 'i', 'r', 's', 't']
Array.from(part) === ['p', 'a', 'r', 't']
```
I realised just now that this really looks like groupBy, so I tried it:
```js
    for (const [k, v] of groupBy((item) => item !== ' ', 'hello world')) {
      console.log(Array.from(v))
    }
```
This prints:
```js
      [ 'h', 'e', 'l', 'l', 'o' ]
      [ ' ' ]
      [ 'w', 'o', 'r', 'l', 'd' ]
```
I also tried using destructuring:
```js
    const [[_1, hello], [_2, space], [_3, world]] = groupBy((item) => item !== ' ', 'hello world')
    console.log(Array.from(hello), _1)
    console.log(Array.from(space), _2)
    console.log(Array.from(world), _3)
```
This returned:
```js
      [ 'w', 'o', 'r', 'l', 'd' ] true
      [ undefined ] false
      [ undefined ] true
```
Which was unexpected initially, but then I realised that groupBy doesn't buffer by design. So if you don't consume the subiterables, this can happen. I'd like to dig deeper into it, to see if it can be improved/fixed.

**Comment by sithmel** [comment]
Yeah, now that I look to groupBy, I think it can be improved to work in all situations.

**Comment by sithmel** [comment]
On a side note: splitting an iterable is a mess, but our implementation is supporting cases that python itertools can't even dream. And this is definitely an achievement

**Comment by sithmel** [comment]
I am experimenting on an enhanced groupBy that will serve as a base of this and splitAt.
