### ISSUE TITLE
compose/pipe/pipeline

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#196]
Just looking now at where we've gotten to. Let me ask some questions.

The `pipe` and `compose` functions are closely related. Would it not better encapsulate their similarities and differences to call them `compose` and `composeRight`? At very least `pipe` could be an alias of `composeRight` and individual coders could choose their style.

I also think that the documentation should not be circularly referential. Each function says it's just the other but backwards. That doesn't get me anywhere, and furthermore the example requires the user to execute two programs in their head in order to find out what the function is syntactic sugar for. It should just say `compose(a, b)` is equivalent to `b(a())`.

Second, why do we have a `pipeline` operator? It doesn't seem to be any more readable than:
```js
pipe(
  () => initial,
  map(x => ++x),
  filter(...),
)
```
As I've perhaps conveyed before I very much dislike APIs that rely on the programmer knowing that, in essence, "one of these similar looking things is not like the other".

**Comment by conartist6** [comment]
Having `pipe` and `pipeline` also violates what I feel should be basic coding conventions, and perhaps something we could add to CONTRIBUTING. If I tell someone who has never seen our API docs, "There are two functions, pipe and pipeline, what do you suppose the difference between them is?" They're going to say, "Line!". When you choose naming conventions to express that two things are similar but different, I think we should always ensure that the difference in the name reflects the difference in the behavior.

**Comment by sithmel** [comment]
I found that "pipe" is a well spread convention for composeRight
* https://ramdajs.com/docs/#pipe
* https://medium.freecodecamp.org/pipe-and-compose-in-javascript-5b04004ac937

"pipeline" was named after the js operator with the same name https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator

The documentation can be improved.

I am not particularly attached to "pipeline" to be honest.

**Comment by conartist6** [comment]
I can live with `pipe` and `compose` if that's standard elsewhere, and if we make the pipe documentation reference `compose` but not the other way around.

I think pipeline will be a syntax when it is ready, and until then people can use `pipe`.

**Comment by KSXGitHub** [comment]
pipe creates a function that executes, pipeline executes. I prefer pipeline.

**Comment by conartist6** [comment]
Why is execution beneficial? Most of our methods take iterables and return iterables and we make rather a big point of saying that we don't do any computation until it's needed.

Executing the composed iterable only makes sense if either `tap` or `consume` is in use, and if it's `consume` it's going to to execute the thing anyway.

So I don't quite see the draw of pipeline executing.

**Comment by conartist6** [comment]
Or rather I should say, executing the contents of the pipe only makes sense if they have side effects, which we generally discourage, except in `tap` and `consume`

**Comment by KSXGitHub** [comment]
> Why is execution beneficial?

It's not about execution, it's about cleanliness. `pipeline` is less verbose when I want to execute it.

**Comment by conartist6** [comment]
OK, so let's bikeshed some names that describe what it does then:

In terms of its relationship to `pipe`, `pipeline` is:
```js
pipe(
   () => iterable,
   fn,
   fn,
)()
```

Here's some names I can think of:
`pipeIterable`
`pipeAndCall`
`pipeSingle`
`pipeOnce`
`applyPipe`
`applyFunctions`
`applyTransforms`

I think I like `pipeOnce` or `applyFunctions`.
Or I still think it would be fine to rename `pipe` to `composeRight` (which is an extremely descriptive and apt name) and this could then still be called `pipeline` which would be consistent with the proposed operator.

In essence what I'm really saying is that while `pipe` and `pipeline` are names that are consistent externally, internal consistency is more important.

**Comment by sithmel** [comment]
I quite like "pipe" as it is now. But I agree that pipe/pipeline can be confusing.

"pipeItem" instead of "pipeline"?

**Comment by conartist6** [comment]
An item is specific terminology we reserve (or should reserve) for the `{done, value}` object, and I don't see what the difference between the functions has to do with items.

**Comment by KSXGitHub** [comment]
How about execPipe?

**Comment by conartist6** [comment]
That'd be ok with me, yeah

**Comment by sithmel** [comment]
I have found this pattern use in clojure.
It is called threading macro:
https://clojure.org/guides/threading_macros
```clj
(defn transform* [person]
   (-> person
      (assoc ,,, :hair-color :gray)
      (update ,,, :age inc)))
```
They solved the problem of naming using **->**

What about "thread" ?

**Comment by KSXGitHub** [comment]
@sithmel "thread" has different meanings and thus ambiguous, it is also not as familiar as "pipe".

**Comment by sithmel** [comment]
It is not ambiguous in JavaScript. But ok, I am not too attached to this idea
