### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#20]
It would be good to get test coverage reporting set up on this library.

Test coverage is already quite high, and people shopping libraries love to see the little badge with a high coverage percentage.

**Comment by sithmel** [comment]
I tried a few times with codecov ... no success. Are you willing to give it a try?

I can promote you to collaborator, that would be well earned :-)

**Comment by conartist6** [comment]
I've never set it up before either, but maybe I'll get lucky! And I would
gladly become a collaborator.

**Comment by sithmel** [comment]
there you are, good luck!

**Comment by conartist6** [comment]
I see you got this finished off. It looks great!
