### ISSUE TITLE
Functions taking multiple iterables should take an iterable of iterables

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#202]
In this ticket I proposed that functions taking multiple iterables should take instead an iterable of iterables (or an iterable of async iterables).
They are:
* concat
* compress
* zipAll
* zip
* merge/collate

This is a follow up from this ticket:
https://github.com/sithmel/iter-tools/issues/185

Here's why I am proposing this:
* consistency with the other functions and curry that works the same way
* interoperability with functions that return an iterable of iterables (fork, partition etc.)

I am registering here different opinions and my answesr:
@conartist6 
> I can see the theoretical elegance of changing the functions which take multiple iterables to take an iterable of iterables, but it seems a bit like sacrificing the common use case for the benefit of the uncommon one.

My answer: uncommon is subjective. In https://github.com/sithmel/iter-tools/pull/167#issuecomment-464402212 I wrote: 
The api should be consistent within itself, to ease function composition. You have functions returning a iterable of iterables (fork, partition, split etc.) and therefore you need corresponding functions that take an iterable of iterables as argument.

@conartist6 in this comment https://github.com/sithmel/iter-tools/issues/185#issuecomment-460717480 wrote:
> I still think that this idea parallelism in data processing is best expressed as code which is written in columns is not robust, and I am particularly unhappy about the idea of making sacrifices from our most basic use cases, which I imagine to have at least 20 times more potential audience than code-in-columns data pipelines. It is because I believe that this library is currently only reaching a tiny fraction of the programmers who it should interest that I have invested time and effort in it. There is at present a bit of a conflict between my interest in serving that yet-unrealized constituency and your interest in refining your existing use cases [...]

What you call "code in column" is function composition. I can argue that is a well spread pattern (in scheme and clojure for example) and I don't see why you say that is not robust. Also there are plenty of APIs that take an iterable (Promise.all, Map, Set for example) and I don't see why this should scare away users.

> Alternatively, you could make a helper function based on your `currying` helper function, which would turn a method from varargs to iterable-of-iterables style. Usage might look like `collectParams(zip)`. I cannot think of any reason a correct implementation would not be possible.

I can consider (as a last resort) creating alternate version of these functions taking an iterable instead of multiple arguments.

@conartist6  again on https://github.com/sithmel/iter-tools/pull/174#issuecomment-466792130
> I think TC39 has spoken on variadic functions. By offering call spread and arguments spread they embraced the pattern, and it makes sense too. Most of the time users of these variadic functions will have separate expressions to pass to each argument. In the less common case that they have an iterable, all they have to do is write `...`. In the even less common case that we are in a pipeline and working exclusively with higher order functions, we now have `apply`.

I would not take the presence of the spread operator as an endorsement. It is just a more practical of using apply

> The variadic arguments arrangement has many desirable properties for the common case. For one, no extra syntax is needed. Another: it is the most optimized, as it passes the variables on the stack instead of having to create an Array.

No extra syntax: not clear what you mean. "most optimized" I won't be surprised if the array is created in the background. But we don't really need to argue on this. We have a benchmark suite, we can just measure it.

> Finally Typescript endorses the pattern. Typescript has an awful time with tuples, and has a tendency to lose their types unless two things happen: 1) the tuple-typed array is defined in exactly the location that it is consumed by a type which supports tuple-typed arrays. and 2) that API has an overload for tuples and an overload for Iterable, since there is no concept of iterables which return a different type at each iteration. This means that in order for the common case type information to not be lost, the user has to make a call of the structure: `variadicFn(arg, [iterableA, iterableB])`. The `[]` cannot go anywhere else, and thus is just dead weight; we may as well have allowed the user to call the function in a variadic manner.

I don't see where the problem is in TS. It should be possible to define an iterator returning iterators. And also I am not sure it is necessary to overspecify the content of the iterables returned by the iterable. I don't see this as worst than the inconsistency on the curry.

**Comment by conartist6** [comment]
Let's start with typescript, as it's the least philosophical discussion. `merge and zip` are the poster children for the problem. Let me show you what I mean in [a typescript playground](https://www.typescriptlang.org/play/index.html#src=declare%20const%20strings%3A%20Array%3Cstring%3E%0D%0Adeclare%20const%20numbers%3A%20Array%3Cnumber%3E%0D%0A%0D%0Adeclare%20function%20merge%3CT%2C%20R%3E(merger%3A%20(...m%3A%20Array%3CT%3E)%20%3D%3E%20R%2C%20mergees%3A%20Iterable%3CT%3E)%3A%20R%0D%0Adeclare%20function%20merge%3CT1%2C%20T2%2C%20R%3E(merger%3A%20(m1%3A%20T1%2C%20m2%3A%20T2)%20%3D%3E%20R%2C%20mergees%3A%20%5BIterable%3CT1%3E%2C%20Iterable%3CT2%3E%5D)%3A%20R%0D%0A%0D%0Aconst%20iterablesToMerge%20%3D%20%5Bstrings%2C%20numbers%5D%20%2F%2F%20this%20has%20type%20Array%3CArray%3Cstring%20%7C%20number%3E%3E%0D%0A%0D%0A%2F%2F%20And%20now%20we've%20hit%20a%20rather%20cryptic%20error.%0D%0Amerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20iterablesToMerge)%3B%0D%0A%0D%0A%0D%0Adeclare%20function%20vMerge%3CT%2C%20R%3E(merger%3A%20(m1%3A%20T%2C%20m2%3A%20T)%20%3D%3E%20R%2C%20...mergees%3A%20Array%3CIterable%3CT%3E%3E)%3A%20R%0D%0Adeclare%20function%20vMerge%3CT1%2C%20T2%2C%20R%3E(merger%3A%20(m1%3A%20T1%2C%20m2%3A%20T2)%20%3D%3E%20R%2C%20m1%3A%20Iterable%3CT1%3E%2C%20m2%3A%20Iterable%3CT2%3E)%3A%20R%0D%0A%0D%0A%2F%2F%20Variadic%20merge%20has%20the%20problem%20too%2C%20though%20a%20better%20error%0D%0AvMerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20...iterablesToMerge)%3B%0D%0A%0D%0A%0D%0A%2F%2F%20Both%20fns%20must%20specify%20the%20mergees%20inline%20then%0D%0Amerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20%5Bstrings%2C%20numbers%5D)%3B%0D%0AvMerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20strings%2C%20numbers)%3B%0D%0A%0D%0A%2F%2F%20And%20if%20this%20is%20necessary%20anyway%2C%20it's%20simpler%20without%20%5B%5D%0D%0A).

**Comment by conartist6** [comment]
Oops, misclick.

**Comment by KSXGitHub** [comment]
@conartist6 Sometime you need to specify type annotation explicitly.

[playground](https://www.typescriptlang.org/play/index.html#src=declare%20const%20strings%3A%20Array%3Cstring%3E%0D%0Adeclare%20const%20numbers%3A%20Array%3Cnumber%3E%0D%0A%0D%0Adeclare%20function%20merge%3CT%2C%20R%3E(merger%3A%20(...m%3A%20Array%3CT%3E)%20%3D%3E%20R%2C%20mergees%3A%20Iterable%3CT%3E)%3A%20R%0D%0Adeclare%20function%20merge%3CT1%2C%20T2%2C%20R%3E(merger%3A%20(m1%3A%20T1%2C%20m2%3A%20T2)%20%3D%3E%20R%2C%20mergees%3A%20%5BIterable%3CT1%3E%2C%20Iterable%3CT2%3E%5D)%3A%20R%0D%0A%0D%0Aconst%20iterablesToMerge%3A%20%5Bstring%5B%5D%2C%20number%5B%5D%5D%20%3D%20%5Bstrings%2C%20numbers%5D%0D%0A%0D%0A%2F%2F%20And%20now%20we've%20hit%20a%20rather%20cryptic%20error.%0D%0Amerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20iterablesToMerge)%3B%0D%0A%0D%0A%0D%0Adeclare%20function%20vMerge%3CT%2C%20R%3E(merger%3A%20(m1%3A%20T%2C%20m2%3A%20T)%20%3D%3E%20R%2C%20...mergees%3A%20Array%3CIterable%3CT%3E%3E)%3A%20R%0D%0Adeclare%20function%20vMerge%3CT1%2C%20T2%2C%20R%3E(merger%3A%20(m1%3A%20T1%2C%20m2%3A%20T2)%20%3D%3E%20R%2C%20m1%3A%20Iterable%3CT1%3E%2C%20m2%3A%20Iterable%3CT2%3E)%3A%20R%0D%0A%0D%0A%2F%2F%20Variadic%20merge%20has%20the%20problem%20too%2C%20though%20a%20better%20error%0D%0AvMerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20...iterablesToMerge)%3B%0D%0A%0D%0A%0D%0A%2F%2F%20Both%20fns%20must%20specify%20the%20mergees%20inline%20then%0D%0Amerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20%5Bstrings%2C%20numbers%5D)%3B%0D%0AvMerge((str%3A%20string%2C%20num%3A%20number)%20%3D%3E%20true%2C%20strings%2C%20numbers)%3B%0D%0A%0D%0A%2F%2F%20And%20if%20this%20is%20necessary%20anyway%2C%20it's%20simpler%20without%20%5B%5D%0D%0A) (line 7)

**Comment by KSXGitHub** [comment]
@conartist6 There's no way to avoid this unless TypeScript itself fix the issue.

**Comment by conartist6** [comment]
@KSXGitHub I am aware that that is one way around the problem. Realistically though a lot of users might forget that they need to do that until they see the error though.

**Comment by conartist6** [comment]
> I won't be surprised if the array is created in the background.

I would! Javascript passes its arguments on the stack. If you want to get into it, take a look at the warnings about exceeding the JS argument length limit on [the MDN page for fn.apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#Using_apply_and_built-in_functions)

**Comment by conartist6** [comment]
> I would not take the presence of the spread operator as an endorsement

What about the fact that the language authors already made the choice? `Array.prototype.concat` could be defined to take an array of arrays to concatenate, but they made it variadic.

**Comment by conartist6** [comment]
> What you call "code in column" is function composition.
I was referring to a particular use of function composition to create two completely separate logical pathways for data processing by specifying `[leftLogic, rightLogic]`. It's not *necessarily* bad. Its not unlike a ternary actually. I'm not arguing that `mergeMulti` or ternaries are never good code, that's not true. What I am saying is that someone who writes the following would be a bad programmer making use of the code-in-columns antipattern:
```js
let result
result = condition ? firstLeftThing(result) : firstRightThing(result)
result = condition ? secondLeftThing(result) : secondRightThing(result)
result = condition ? result : thingThatOnlyRightDoes(result)
```

> Also there are plenty of APIs that take an iterable (Promise.all, Map, Set for example) and I don't see why this should scare away users.

`Map` and `Set` have overriding concerns that guide the choice to use iterable like, well, the need to be able to construct them from iterables, including other Maps, Sets, and functions like `entries`. Plus it needs to be possible to construct Maps and Sets with more than 65536 items, which is the max argument length limit.

`Promise.all` and `Promise.race` are more direct analogs, and I do think they support your point. I don't really know why a different choice was made with those functions.

**Comment by sithmel** [comment]
Let's hypothetically say that at some point we want to support a "filler" argument to zipAll:
```js
zipAll({ filler: 0 }, [[1, 2, 3], [4, 5]]) // [1, 4] [2, 5] [3 ,0]
```
It would make sense to support curry here, the same way we do for the other functions:
```js
const zipAllZero = zipAll({ filler: 0 })
zipAllZero([[1, 2, 3], [4, 5]]) // [1, 4] [2, 5] [3 ,0]
```
This would be perfectly consistent with the rest of the functions.

But If I have:
```js
zipAll({ filler: 0 }, [1, 2, 3], [4, 5]) // [1, 4] [2, 5] [3 ,0]
```
I need to use another pattern that is oddly different:
```js
const zipAllZero = (iter) => zipAll({ filler: 0 }, ...iter)
```

**Comment by conartist6** [comment]
The current implementation of curry would require that. My implementation of curry, to be found in the collate branch, does not.

It correctly handles:
```js
const zipAllZero = zipAll({ filler: 0 })
zipAllZero([1, 2, 3], [4, 5])
```

**Comment by conartist6** [comment]
By the way that example is also an excellent validation of our earlier decision not to treat objects as being coercible to iterables.

**Comment by sithmel** [comment]
> * consistency with the other functions and curry that works the same way

The new variadic curry proposed here https://github.com/sithmel/iter-tools/pull/203 solves the issue related to currying and consistency.

> * interoperability with functions that return an iterable of iterables (fork, partition etc.)

This is not addressed though.
And it creates an avoidable obstacle in what I still think is a good pattern
```js
pipe(
  csvReader(...),
  asyncFork,
  applyMulti([readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])
  asyncZip,
  asyncFork,
  applyMulti([pipe(asyncMap(...), writeCSV(...)), getAttachment(...)]),
   ...
)
```

Also I don't see clear advantage of spreading the iterables as different arguments. Rather than aesthetic taste at least.

**Comment by conartist6** [comment]
Well if you do that the `merge(apply, ...)` pattern is pretty much shot. For consistency the merger signature would change from `mergeItems(a, b, c)` to `mergeItems([a, b, c])` (notice the ugly `call(apply)`). The partial technique wouldn't work either because you either specify the iterable or iterables or you don't. So you end up with:
```js
pipe(
  csvReader(...),
  asyncFork,
  iterableOfIterables => merge(call(apply), [[readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)], iterableOfIterables])
  asyncZip,
   ...
)
```

I think you'd be doing serious damage to the libraries effectiveness in working with higher order iterables, and then either using `applyMulti` to put a rather small band aid on the problem or worse, inventing a whole new category of *multi* functions that shouldn't need to exist.

In contrast if we leave things the way they are the code becomes:
```js
pipe(
  csvReader(...),
  asyncFork,
  merge.partial(apply, [readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])
  apply(asyncZip),
   ...
)
```

**Comment by conartist6** [comment]
In essence what I'm getting at is that higher order code is very dependent on the names of things to be readable since a whole layer of implementation and call structure is obscured. By sticking with the model the language itself puts forth (functions take multiple arguments are return a single value) you get names (like call and apply) that describe a model that people already understand.

Eventually even the moderately ugly `.partial` calls will no longer be necessary in that example. Take a look at what it becomes in the near-ish future we have an accepted proposal for pipeline and partial application operators:
```
let result = csvReader(...)
  |> asyncFork(2)
  |> merge(apply, [readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)], ...?)
  |> zip(...?)
```

**Comment by sithmel** [comment]
> Well if you do that the `merge(apply, ...)` pattern is pretty much shot. For consistency the merger signature would change from `mergeItems(a, b, c)` to `mergeItems([a, b, c])` (notice the ugly `call(apply)`). The partial technique wouldn't work either because you either specify the iterable or iterables or you don't.

This is one of the reason why I don't like the approach using asyncMerge and partial.
The fact itself that you need *partial* is the proof that you are shoehorning the output of fork into the input asyncMerge.

> ... a whole new category of _multi_ functions that shouldn't need to exist.

I imagined applyMulti to be a simple utility function, like compose and pipe. What else do you think we would have in this _multi_ category ?

> ...sticking with the model the language itself puts forth...

This proved to not to be the case (see Promise.all, Map, Set)

The thing that is still not clear to me is what real advantage there is in using multiple arguments instead of an iterable of arguments. Apart style taste. Because so far I found none.

On the other hand I admit there is not such an incredible advantage in using iterable or iterables either.
As soon as you get an iterable of iterables from fork/partition you will probably want to apply different transformations (applyMulti) and then obtain a single iterable again using zip/merge. That's the case I want to address.
I could write:
```js
pipe(
  ...
  ([iter1, iter2, iter3]) => asyncZip(readDataFromMongo(..., iter1), readDataFromApi(..., iter2), generateNewItem(..., iter3)),
   ...
)
```
instead of
```js
pipe(
  ...
  applyMulti([readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])
  asyncZip
   ...
)
```
But why I should ?

**Comment by conartist6** [comment]
`Map` and `Set` are not good examples for reasons I have stated.

Let's look at what uses variadics then:
- [The ES language](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)
- [rxjs](https://rxjs-dev.firebaseapp.com/api/index/function/concat)
- [ramda](https://ramdajs.com/docs/#concat)
- [Immutable.js](https://immutable-js.github.io/immutable-js/docs/#/Collection/concat)
- [underscore](https://underscorejs.org/#union)
- [lodash](https://lodash.com/docs/4.17.11#concat)
- [Python iter-tools](https://docs.python.org/2/library/itertools.html#itertools.chain)

I don't know what else I can say. I think we'd need a really good reason to break with this pattern.

**Comment by conartist6** [comment]
I could see breaking with tradition if it were obvious that such a change would be necessary in order to use powerful new tools or features, but it's the opposite! This whole discussion is about using these functions in a pipeline, but pipelining is a standards track language feature likely to be paired with partial application which, while it will be able to manage unbound parameters, **will not be able to insert into arrays**.

**Comment by sithmel** [comment]
Thanks for bearing with me so far @conartist6 . I really appreciate your patience.

The only reason I could find for having iterable of iterables as argument for zip/merge is to allow piping the output of fork/partition through them.

I would be happy finding a good solution to fix this.

Some ideas:

## iterToArgs
A decorator that converts a function to use iterable of iterables:
```js
pipe(
  asyncFork
  applyMulti([readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])
  iterToArgs(asyncZip)
   ...
)
```

## vanilla
This is here for reference. It is not horrible. I don't like that you have to specify the iterables twice.
```js
pipe(
  asyncFork
  applyMulti([readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])
  ([_1, _2, _3]) => asyncZip(_1, _2, _3)
  // or (...args) => asyncZip(...args)
   ...
)
```

I was also thinking renaming "applyMulti" to "applyToItems" and at this point change the signature according with the other functions:
```js
  applyToItems(readDataFromMongo(...), readDataFromApi(...), generateNewItem(...))
```

**Comment by conartist6** [comment]
So my thoughts on this you've seen already:
```js
pipe(
  asyncFork
  merge.partial(apply, [readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])
  apply.partial(asyncZip)
   ...
)
```
Apply essentially **is** iterToArgs. I've been thinking up til now that we wouldn't curry call or apply, which is why you see it used with `.partial` in order to force it to wait for more arguments. Certainly call can't safely be curried since there's a chance the function is the only argument you're going to get, however now that I think about it it doesn't seem so inappropriate to require the iterable parameter to apply, in which case it could be curried using `variadicCurryWithValidation` and the above could could be shortened to `apply(asyncZip)`.

Once again the reason I'm pushing this proposal is that it seems to be in alignment with what is likely to be the language's long term solution: partial application. It becomes:
 ```js
  |> asyncFork
  |> merge(apply, [readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)], ?)
  |> apply(asyncZip)
```

**Comment by sithmel** [comment]
> `apply` **is** `iterToArgs`

a curried apply, I didn't think about it. I like it!

> ```merge.partial(apply, [readDataFromMongo(...), readDataFromApi(...), generateNewItem(...)])```

the partial method feels completely out of place in this library. 

Thinking about apply/applyToItems:

```js
apply(func)(arg)
// func(...arg)
```
```js
applyToItems(func1, func2, func3)([arg1, arg2, arg2])
// func1(arg1) func2(arg2) func3(arg3)
```
Note as the arguments are not spread, and this feels odd if compared to apply behaviour

Note also that applyToItems would become the odd one now. Given that would be the only function taking as input an iterable od iterables.

**Comment by KSXGitHub** [comment]
I find `func.partial()` pattern has 2 disadvantages:

1. **Tree-shaking:** `func.partial` is most likely a local method (i.e. a local function that is attached to the main function inside a helper function). Whilst some bundlers may be able to tree-shake global methods, none dares to tree-shake local method.

2. **Compression:** `partial` is a property name, not a variable name. Compression tools such as uglify-es won't shorten a property name.

**Comment by conartist6** [comment]
I think whether or not partial can be tree-shaken is inconsequential, as is its uglification. It's a small method with a relatively short name, a pretty specialized use case, and maps to a future language feature. We need not open the door wide to adding lots more similar property-based methods, and once language-level partial application support lands in transpilers we would encourage people to use that instead -- indeed `.partial` would ease the transition, and ultimately our `partial` would be deprecated.

But since I'm getting pushback from both on it, it doesn't need to exist. The expression can be written as `_ => merge(apply, [...], _)`, which is fine.

I dislike `applyToItems` because apply is the controlling verb, and theres no indication of this rather out-there behavior of taking multiple functions.

My part in this has been to consider multi-application as a novel use case for the core functions, and ensure that they are able to rise to that challenge. I have what I want, which is the ability to express this functionality in a way that is optimized for readability. I try always to prefer ease of reading over ease of writing in my code (as it is likely be read often and changed rarely), so that is all I need. I leave it to you to decide whether there should be a sugar method that optimizes this use case for writability, as only someone who is actually using it knows for sure what all the relevant factors are. I would however encourage you to run a test: find a real use case in your codebase and try expressing it with both `applyMulti` (or whatever you decide to call it) and `_ => merge(apply, ..., _)`. Then find a coworker or two who have seen that code before and ask them which they would prefer to read, and to write.

**Comment by sithmel** [comment]
> _ => merge(apply, [...], _)

is ok, but there is still one problem.

```js
pipe(
  asyncFork
  _ => merge(apply, [map(square), filter(even)], _),
   ...
)
```
won't work the way I need because it will be equivalent to:
```js
const [_1, _2]  = asyncFork(iterable)

[map(square)(..._1), filter(even)(..._2)]
// while it should:
[map(square)(_1), filter(even)(_2)]
```
So I guess what we really need in this case is "call":
```js
  _ => merge(call, [map(square), filter(even)], _),
```
I still prefer the short method, not because is faster to write, but easier to remember.

I am going to run this through a couple of colleagues of mine to get some feedback.

**Comment by conartist6** [comment]
Ah, yes, you are right.

**Comment by conartist6** [comment]
And I'd say that being easier to remember is still technically ease of writing, in that the it places the burden on the writer not the reader. By the way if we don't add the method this is a perfect example of something that could go in the cookbook, wh

**Comment by conartist6** [comment]
And I'd say that being easier to remember is still technically ease of writing, in that the it places the burden on the writer not the reader. By the way if we don't add the method this is a perfect example of something that could go in the cookbook, which would be a great and pretty accessible place to go look it up if the exact code for the pattern does not seem particularly memorable. It's only really one click further away than the main documentation.

**Comment by sithmel** [comment]
I had a chance to show a couple of colleagues all the different options.

**merge/apply** resulted the most obscure for everybody. One also pointed (after my explanation) that what we call "merge" looks like [ramda's zipWith](https://ramdajs.com/docs/#zipWith) and merge has a different meaning in ramda.

I found zipWith(call) better than merge(call) or merge(apply) and it has the advantage of taking as argument 1 function and 2 iterables. So it doesn't require to invent anything strange to be curried.

Even zipWithCall as a single function is not too bad.

**Comment by conartist6** [comment]
Great! I have no problems with calling `merge` `zipWith`. It looks to me though like ramda's `zipWith` has the exact same signature as the proposed `merge`, so I don't quite understand what you're saying about the situation with currying being different.

I maintain my neutral stance on whether we'd support `zipWithCall(...)` in addition to `zipWith(call, ...)`.

**Comment by conartist6** [comment]
`merge` means something different in rxJS (basically our proposed asyncCollateReady) and lodash (basically Object.assign), so `zipWIth` does seem less ambiguous.

**Comment by sithmel** [comment]
Merge takes multiple input iterables zipWith apparently takes only 2 iterables (in ramda)

**Comment by conartist6** [comment]
Ours should still take a plural number I think. We could of course tell our variadicCurry that it has a minimum of three arguments (the function and two mergees), but that could result in some really surprising behavior if the iterables are spread into the function and there only happens to be one (which may be something that can only be determined at runtime and is controlled by factors far away). Example:

```js
zipWith((...args) => Object.assign({}, ...args), ...iterables)
```

Someone is going to be very surprised when they get a function back instead of an iterable of objects.

**Comment by sithmel** [comment]
cc https://github.com/ramda/ramda/issues/707

**Comment by sithmel** [comment]
The special utility function seems to me the only viable option at this point.
but zipWith* should be ruled out if used instead of merge

So now we have an unnamed utility function again.

Without a better option I would add an entry to the cookbook. My colleagues yesterday didn't mind too much of using vanilla.

**Comment by conartist6** [comment]
I'm very confused. `zipWith*` is a viable option but you've ruled it out "if used instead of merge" I don't understand. Let's add to the cookbook for now. It's always easy to add a method later.

**Comment by sithmel** [comment]
With zipWith* I mean the utility function "zipWithCall, or zipWithApply" that is basically the equivalent of applyMulti.
If we use zipWith as new name of merge, having a function with a similar name would only bring confusion.

**Comment by conartist6** [comment]
OK. I'm going to try to get the currying PR merge-ready.

**Comment by sithmel** [comment]
I'll leave this opened until I manage to add an entry to the cookbook

**Comment by sithmel** [comment]
done
