### ISSUE TITLE
An idea of pipe/pipeline

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#204]
[playground link](https://www.typescriptlang.org/play/#src=%2F%2F%20implementation%0D%0A%0D%0Aclass%20Box%3CValue%3E%20%7B%0D%0A%20%20%20%20constructor(%0D%0A%20%20%20%20%20%20%20%20public%20readonly%20get%3A%20()%20%3D%3E%20Value%0D%0A%20%20%20%20)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20pipe%3CArgs%20extends%20any%5B%5D%2C%20Result%3E(%0D%0A%20%20%20%20%20%20%20%20fn%3A%20(x%3A%20Value%2C%20...args%3A%20Args)%20%3D%3E%20Result%2C%0D%0A%20%20%20%20%20%20%20%20...args%3A%20Args%0D%0A%20%20%20%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20Box(()%20%3D%3E%20fn(this.get()%2C%20...args))%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20startPipe%20%3D%20%3CX%3E(x%3A%20X)%20%3D%3E%20new%20Box(()%20%3D%3E%20x)%0D%0A%0D%0A%2F%2F%20example%0D%0A%0D%0Aconst%20foo%20%3D%20startPipe(123)%0D%0A%20%20%20%20.pipe(first%20%3D%3E%20(%7B%20first%20%7D))%0D%0A%20%20%20%20.pipe((a%2C%20b%2C%20c)%20%3D%3E%20(%7B%20a%2C%20b%2C%20c%20%7D)%2C%20'b'%20as%20'b'%2C%20'c'%20as%20'c')%0D%0A%20%20%20%20.get()%0D%0A)

```javascript
// replace pipe
const myFunc = startPipe(initialValue).pipe(foo).pipe(bar).get

// replace execPipe
const myValue = startPipe(initialValue).pipe(foo).pipe(bar).get()
```

**Comment by conartist6** [comment]
I really think `pipeExec` is fine, and it's only for the short term. In the long term we'll have the language's pipeline operator.

**Comment by KSXGitHub** [comment]
> I really think `pipeExec` is fine

The problem lies within TypeScript. How many overloads of `pipe`/`pipeExec` we have to define to be sufficient?

> In the long term we'll have the language's pipeline operator.

I do agree, but until then, TypeScript users still have to use helper functions.

**Comment by conartist6** [comment]
Ah, I suppose that is a bit tricky. We can define a decent number though.

**Comment by sithmel** [comment]
@KSXGitHub I think I understand the issue (for TS to have multiple signature of pipe/pieExec with multiple arguments).

I would avoid adding another different method to combine iterables.

I think that would be a nice package by itself.
