### ISSUE TITLE
entries, keys, values

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#209]
These currently rely on `inst.hasOwnProperty(name)`. This is incorrect, they must use `Object.prototype.hasOwnProperty.call(obj, name)`. This is because objects created with `Object.create(null)` do not have `hasOwnProperty` and still should work with these methods.

**Comment by conartist6** [comment]
I pushed a fix directly. Could we make a 6x branch and cherry-pick the fix as a patch release? I could use the amended code sooner rather than later.

**Comment by sithmel** [comment]
released 6.2.4

**Comment by conartist6** [comment]
Thanks!
