### ISSUE TITLE
Suggestion: Exponentiation (for lack of a better term)

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#212]
It is a handy function that "multiplies" an iterator with itself for `n` times.

```javascript
const pow = (iter, n) => product(...repeat(iter, n))
```

**Comment by sithmel** [comment]
I think that would be a great addition for the cookbook :+1:

**Comment by sithmel** [comment]
As of now you can consume an iterable only once, so what you proposed doesn't always work.
```js
pow([0, 1], 2); // this works
pow(range(2), 2); // this doesn't works
```
This works always:
```js
const pow = (iter, n) => product(...slice(2, fork(iter)))
```
I updated the cookbook with the example

**Comment by KSXGitHub** [comment]
> This works always:
> 
> ```js
> const pow = (iter, n) => product(...slice(2, fork(iter)))
> ```

You meant `slice(n, fork(iter))`?
