### ISSUE TITLE
Proposal: metaprogramming with babel macros

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#213]
I think in the long term we're going to have to do something about the amount of code duplication in iter-tools. The bulk of it stems from the fact that most of our implementations have almost identical copies for the async forms.

I do not think that we can or should want to try to consolidate the sync vs async methods to share code at runtime. I can expand more on my reasons for that, but perf is high among them, given the complexity that would be involved. We could however share code between implementations at compile time, and I think we should.

Babel macros are pretty cool, and a relatively recent feature of babel: they allow you to import a transformation into a source as a symbol. The macro is then passed the AST node that is called on, and given an option to inspect and transform it. Here's what it might look like:

```js
import a from "./macros/async";
a(function someMethod() {
  a(for(const item of iterable) {
    ...
  })
})
```

Which, when transpiled by babel, would be split into two outputs:
```js
function someMethod() {
  for(const item of iterable) {
    ...
  }
}
```
and
```js
async function someMethod() {
  for await (const item of iterable) {
    ...
  }
}
```

Fortunately in order to keep ourselves sane we already make sure that our sync and async implementations looks as similar to each other as we can make them. But this method of working gives us a lot of flexibility as well. For one it is opt-in not opt-out, so we can use it only where it really makes sense. It would even allow us to insert slightly different custom code into each method if we needed to:
```js
import isAsync from "./macros/is-async";

if (isAsync) {
  // Only the contents of one block or the other would be present in output
  // ...
} else {
  // ...
}
```

Some more thoughts:
- Babel macros are supported on [astexplorer.net](https://astexplorer.net/), making it relatively easy to test them out and figure out what the correct transformation code to apply is.
- Because the macros have resolvable imports it will be far easier for new contributors to the project to discover the relevant transformation code and understand how the final code is generated.
- Eventually (though it would not be necessary immediately) we could develop macros that would help us manage our tests for sync and async version of a function. This could help considerably. As low hanging fruit, the macros could easily allow us to generate real inputs which were sync for sync tests and async for async tests, instead of only testing the code paths where async methods are called on synchronous iterables. Consolidating the tests to the extent that they validate basic method behavior for both sync and async impls would also give us more energy to write tests for what may be genuinely different between the two versions.

**Comment by sithmel** [comment]
I can see we have some degree of repetition, but I am not sure it is worth to add such a complex element.
I am afraid this will be raising the (already high) bar, for new contributors.

**Comment by conartist6** [comment]
It's certainly a trade off. I worry that if we don't tackle the repetition our test coverage is going to remain inconsistent and incomplete, and that the long term maintenance of the library will become a lot of work.

Even now there's a burden on new contributors. Most of them would realistically come to the project after encountering a bug with a sync utility, contribute a fix to the sync version, and then they would need to figure out how to make the corresponding change to the async version and write all their code (app, type, test) again.

As I've said, I also think that babel macros in particular can offer a far better story here, particularly for new contribs, than any way that this would have been accomplished in the past.

**Comment by conartist6** [comment]
In essence I think we'd have to teach a new contrib exactly what rules the macro applies anyway in order for them to change both sets of files (e.g. use `for .. await`, `ensureAsyncIterable`, and `asyncToArray`. They're pretty mechanical transformations, but what is the advantage in having to teach every contrib these rules instead of just doing that work for them?

**Comment by conartist6** [comment]
Let's say you're a casual user of an open source library whose API exposes slight variants of basically the same logic. You have a fix or improvement you need to make. You go to the codebase, and discover that almost all the code in the library is copy-and-paste duplicated. There's two full copies of the sources, which are kept consistent by hand. If it was me, I'd be discouraged from contributing to that library, and would start thinking about how to get it out of my codebase. After all subtle bugs and divergences are not just a risk but the logical eventuality of such duplication, especially on such a large scale.

This is why one of the most repeated adages of software development is Don't repeat yourself. DRY isn't just a magical win though, you're always adding complexity to reduce duplication. It's just that the software community has decided as a whole, emphatically, that this is worth it.

I'm not claiming some radical insight here, I'm just claiming that we should follow the same practices that everyone else does when writing software, that we have a problem which requires a technical solution of some kind, and that I have noticed a potential solution which minimizes the exact concerns which are brought up here.

**Comment by sithmel** [comment]
I imagine at one point we will finally be in the position to abandon any transpilation step and go vanilla (I am looking forward to it).
The way you propose we will have to deal with transpilation forever. Dealing with things such as sourcemaps, non-descriptive stackstraces etc.

**Comment by conartist6** [comment]
Yes, we would have a transpilation step forever. Personally I think babel is here to stay for the long term, but actually I think that's irrelevant. Firstly, we don't need any source maps. In fact the kind of macro transformation step I'm proposing would not, should not have source maps. We need the sources to be javascript, because nobody wants to see an invented macro language as a program source.

Now this is up for discussion, but one reason I think we can get away with not having source maps, is that I think it would not be unreasonable to check in the transpiled sources. After all we want people browsing github to easily be able to see javascript that is going to get executed, and the history of it as well. We don't want them to clone, check out an old tag and build just to find out for sure how an old version works. All the generated files can include a header warning people not to modify them directly (would be transpiled out on web). The comment would even include instructions for modifying the contents of the generated file, including the name of the template that would need to be changed, and the command to be run to trigger the generation. We would configure Travis to reject PRs in which running the generation step results in git changes, something which I already have the code for doing elsewhere.

We can debate the best directory structure if you think this is moving forwards with, but at simplest we don't need to change it at all. A module would just potentially have a `module.template.js` (or `.mjs`?) file which would result in the generation of `module.js` and `async-module.js` files.

**Comment by conartist6** [comment]
And again checking in the sources also helps contributors. They will first likely look at the generated files, which is what they will have seen in their debugger -- either as a source map or because their level of support was decent enough to run the code directly. It should be fairly obvious to them then when they see the result of generating the template first, how the template works. Inferring meaning from context is natural for people, far more natural than just seeing the template and having to do guesswork to determine what the result of evaluating it might be.

**Comment by conartist6** [comment]
I am closing this as this technique is now deployed in the codebase. Work is outstanding still on the typescript types, but that will be tracked in #237.
