### ISSUE TITLE
Consider deprecating iter

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#23]
I think `iter` should probably not be part of the library's public API surface.

Strings and arrays are already iterables. A deprecation notice could warn users when an object is passed to `iter`, informing them that they should use entries instead.

Internally a function called iter could continue to be used with the same basic responsibility of making an iterator out of an iterable.

**Comment by conartist6** [comment]
@sithmel Any thoughts on this?

**Comment by conartist6** [comment]
I'm looking at Immutable Sequences and starting to try to put together the Sequence library. Interestingly their sequence constructor has a lot of functionality built in of the kind that I've been recommending be pulled out of iter.

The docs are here:
https://facebook.github.io/immutable-js/docs/#/Seq.Set/entries

I still think that iter-tools is significantly lower level and that it shouldn't make a guess about using objects as iterables.

However when we pulled out the case that checked to see if `typeof iterable.next === 'function'` we lost the ability to run these methods on iterators. I think that may have been a mistake.

**Comment by sithmel** [comment]
Probably the current implementation doesn't make a lot of sense.

I added the possibility to pass a generator with its arguments because I assumed obj[Symbol.iterator] could possibly be a function that takes arguments, but this is not true, according to the specs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator

So let's recap:

We have **generators**. And they are just functions:
```js
const generator = function * () { yield 10 };
typeof generator === 'function'
typeof generator.next === 'undefined'
typeof generator[Symbol.iterator] === 'undefined'
```

**iterators** are objects instead and they have Symbol.iterator as attribute:
```js
const iterator = generator()
typeof iterator === 'object'
typeof iterator.next === 'function'
typeof iterator[Symbol.iterator] === 'function'
```
Very confusingly the Symbol.iterator attribute returns a generator, and this is not even the same initial generator:
```js
typeof iterator[Symbol.iterator]() === 'object'
typeof iterator[Symbol.iterator]() !== generator
```

So based with this explanation, we don't need ```typeof iterable.next === 'function'``` as we have ```iterable[Symbol.iterator]```.

But let me go on. Objects can be iterable if they have a [Symbol.iterator] attribute:
```js
const array = [1, 2, 3]
typeof array === 'object'
typeof array.next === 'undefined'
typeof array[Symbol.iterator] === 'function'
```

The main goal of iter should be to flat out the differences between iterator and iterable object.

So the simplest implementation could be:

```js
function iter(item) {
  return item[Symbol.iterator]()
}
```
That should work for objects and iterators:
```js
iter([1, 2, 3]).next // this is a function
iter((function * () { yield * [1, 2, 3]})()).next // this is a function too
```

Returning an empty iterator for null is convenient.

We can remove "entries", now that is a standalone function.

So the new version could simply be

```js
export default function iter (iterable) {
  if (iterable == null) {
    return emptyArr[Symbol.iterator]()
  } else if (iterable[Symbol.iterator]) {
    return iterable[Symbol.iterator]()
  }
  throw new Error('...')
}
```

**Comment by conartist6** [comment]
I think we both got a bit confused.

> iterators are objects instead and they have Symbol.iterator as attribute:

This isn't true. Iterators are objects with `next()`, no more no less.
Iterables have `[Symbol.iterator]() which returns an iterator`
_Generator functions_ are neither iterables nor iterators, yet their return values (generators) are both at the same time. But really for our purposes I think it is safe to ignore the fact that generators are iterators.

The iter-tools library code works on iterables, because that's what `for .. of` works on. However, iter-tools does not assume that is able to iterate over any iterable more than once. This is good, because as I just reminded myself, iterables themselves are not guaranteed to be iterable more than once, as is the case with generators. It is up to the programmer to know whether it is safe to iterate over an iterable more than once.

Custom iterators can exist, i.e. ones not implemented with generator functions. The library should support them, one way or another. However, as we've already discussed, there's no good way to know at runtime whether they are iterators. You can check and see if `typeof next` is `function`, but that's hardly a guarantee. The solution to this problem is the one that generators use already: put your custom generator into an object with a `[Symbol.iterator]()`. Now you pass the object around, and it can easily be determined reflectively what it is. This is the exact strategy that generators use already.

What this suggests to me is that `iter` should in fact go away. The library should only accept iterables as input, and thus there is no need to do conversion of any kind. What I think should be offered is this function:
```js
function iterable(iterator) {
  return { [Symbol.iterator]: { return iterator } }
}
```

This way if the programmer knows at compile time that they are holding a custom generator, they simply use that function tag it before passing it into iter-tools. It would look like this:

```js
import { iterable, slice } from 'iter-tools'
const myRangeIterator = {
  value: 0,
  next() {
    return { value: this.value++, done: false }
  }
}

expect(slice(3, iterable(myRangeIterator)).toBeIterable(expect.yields(1, 2, 3))
```

**Comment by conartist6** [comment]
So actually here's my final suggestion:
Remove iter from the public API.

Retain it internally with this implementation:
```js
const emptyArr = []
export default function iter (iterable, ...args) {
  if (iterable == null) {
    return emptyArr[Symbol.iterator]()
  } else if (!iterable[Symbol.iterator]) {
    throw new Error('The argument is not an iterable, or null')
  }
}
```

**Comment by conartist6** [comment]
Note: immtuable actually also tries to ingest generators presently. I'm pushing for that to change here: https://github.com/facebook/immutable-js/issues/1456

**Comment by conartist6** [comment]
Also we'd tentatively removed support for treating objects as iterables in all iter-tools APIs (by removing the case from `iter`). I think with my proposed changes it would be safe to support them still. It's an interesting decision.

On one hand if no APIs treat objects as iterables, we can throw an error and any call site that was passing an iterator, could get a nice message, possibly even tailored to tell them exactly what went wrong. It also means that in the future people will explicitly use `entries()` to get what is now the default behavior. I like that a lot because of the potential for confusion. Iterable is already a term with objects (since they can be iterated with `for ... in` and can have iterable and non-iterable properties etc. In that context `entries` will make lots of sense to any reader of the code that uses it, as they will already likely be familiar with the semantics of `Object.entries`, and thus have an existing (and correct) intuition about exactly what is going on.

On the other hand it's going to be a rude awakening to anyone who was making heavy use of that functionality.

**Comment by sithmel** [comment]
Previous implementation was based on a few misconception of its author: myself :rofl:
