### ISSUE TITLE
Code generator not well behaved during git operations

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#230]
So part of what's going on is a simple race condition. During git operations a lot of watched files change all at once. Every file that changed needs to update the monolithic files, which is to say files like gitattributes which contain lists based on everything which was generated. So basically that operation has two problems: it races, and the monolithic files get hammered with writes.

This isn't such a big deal to fix, but I still worry. For example, what if you are rebasing through quite a few commits and one of them is dirty, which is to say that the generator thinks there should be changes. The generator will try to make the changes, but it will be racing git, which will have moved on to trying to apply the next commit. Also there will be many situations where the output of the code generator changes. This could happen due to explicit changes or due to external factors e.g. because babel-minify updates. We want to be sure that the generator doesn't start trying to emit changes that only exist because previous generated code was created with an older version of the generator.

For this reason I think it probably makes sense, in addition to resolving the race condition and throttling writes to monolithic files, to lock the generator from making changes while a git operation is in progress. I'll have to look into how to do this correctly.

**Comment by conartist6** [comment]
I think the key is to check for the existence of `.git/index.lock`.

**Comment by conartist6** [comment]
OK I've just pushed changes that make significant improvements to the readability and functioning of the code generator. It now seems to behave itself around git.

There are still potential issues surrounding rebases that cross code generator updates. For now if you need to rebase across an update to the code generator (such as the one I just pushed) be sure to stop the generator first.

@sithmel If you encounter issues using the generator, please open an issue (or reopen this issue) so that I can take a look.

**Comment by sithmel** [comment]
ok, shall I close this then ?
