### ISSUE TITLE
What is asyncThrottle for?

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#231]
Here is the documentation:

"It wraps an async iterable and ensures that every item is yielded with an interval of n ms"

That doesn't tell me much. Is it supposed to be a clock? That's what it looks like from the sources, based on the fact that it compensates for timing variations inherent in setTimeout. But it doesn't behave that much like a clock, given the pace of items yielded from the async source iterable is also a factor.

Actually regardless of what this function is for I think we should create utilities for making clocks. We could have a sync generator, `clock()`, which would simply yield `Date.now()` at every step, and we could have an async generator `tick()` which would be like this method but expect a synchronous source. Then you could `tick(1000, clock())` and if you were writing a clock in JS all that would be left would be to format and display. I can seeing this being awesome, as I have surveyed JS clock utilities and found that most of them aren't sub-second precise (to the best of their abilities) as they do not even attempt to compensate for timer drift.

I can also see a possible usage of `asyncThrottle` for polling, but in my mind that doesn't work very well. For example if I am polling something at 100ms intervals, I expect an update every 100ms even if the update is that nothing has changed. This function can't do that with an async source iterable, because it must await each item from the source.

In general it isn't too hard to create polling either, you can just write:
```js
while(await delay(ms)) {
  poll();
}
```

If the intent is to mirror `_.throttle`, the assumption behind that method is that a later call invalidates an earlier one, meaning that it is OK to drop certain calls. This is certainly possible with async iterables, but it's not what's happening here, since this iterable will yield every input in its output.

Anyway, curious to hear what the intent was.

**Comment by sithmel** [comment]
I think a better description would have been:

"It wraps an async iterable and ensures that every item is yielded with an interval of **at least** n ms"

> We could have a sync generator, clock(), which would simply yield Date.now()

I like the idea! Maybe, only drawback is that it might be simplistic to deserve a function

> If the intent is to mirror _.throttle ...

No, It was not. but I admit the idea is interesting.

**Comment by conartist6** [comment]
So have you used the function? What did you envision using it for?

**Comment by sithmel** [comment]
I did.
I had a migration pipeline that collected data and sent those to another service.
I had to slow down the data flow to avoid flooding the service with requests.

**Comment by conartist6** [comment]
Hmm ok that makes sense.
