### ISSUE TITLE
Place methods in folders?

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#233]
I think there is a case to be made for placing the files associated with a method in a folder. It's getting pretty difficult to navigate around through the flat src directory, and I only plan to make it harder as I use our generator strategy to eliminate the duplication present in our typescript types. At that point each method will contribute 5 files to the `src` directory.

The folder structure I propose would look like this:
```
method/
    async.js
    async.d.ts
    index.js
    index.d.ts
    index.template.js
    index.template.d.ts
```

I can think of several benefits. In most editors folders show up above files, making it easier to find the main index.js and index.d.ts files (they would be at the bottom). It would be easier to read the src directory as a listing of the supported methods too.

A downside would be that this would be significantly less clear for methods which have only async variants. Putting them in a folder whose name is stripped of the async prefix suggests that there is a sync version when there isn't, but naming the folder `asyncMethod` creates two different ways of importing async files from inside the library, which is unreasonable to expect people to keep track of.

I need to keep thinking about what a reasonable solution to this particular problem might be.

**Comment by conartist6** [comment]
Actually I think we can just change the template naming convention from `method.template.js` to `$template.js`. This way all the templates will be sorted above the non-templates, and also all the whole import structure resolves again.

**Comment by conartist6** [comment]
I have that change to `$method.js` queued up. @sithmel can you confirm that you don't have any concerns around shifting the naming convention?

**Comment by sithmel** [comment]
not at all. Go for it
