### ISSUE TITLE
chain/zip/zipLongest signatures

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#24]
since we changed the signature of zip and ziplongest to take an array of iterators, I think that chain would be more consistent taking an array of iterables.

**Comment by conartist6** [comment]
If I had to choose I'd rather put zip back the way it was. I think compose is an essential utility. It should be used a lot (thus readability is important), the API is at very low risk for changing in a way that requires adding extra parameters, and not requiring the array brings iter-tools in line with what other libraries which offer the same function do.

**Comment by sithmel** [comment]
I liked the idea that you can batch/do something in the middle/chain to go back to the initial format

**Comment by conartist6** [comment]
I don't understand. You seem to be suggesting that the difference between having an array and not alters what code it is possible to write. As far as I know, spread syntax means that arguments can already be treated like an array in almost every respect.

e.g.: `console.log(...['foo'], 'bar', ...['baz']) // > foo bar baz`

**Comment by sithmel** [comment]
The real pain is zipLongest as it takes as first argument the placeholder:
```js
zipLongest(null, iter1, iter2)
```
Using an array would be cleaner:
```js
zipLongest(null, [iter1, iter2])
```
maybe in the future we could add other options so it could be convenient having something like this:
```js
zip([iter1, iter2]) // same old zip
zip({ fill: null }, [iter1, iter2]) // zip longest
```
I think having { fill:null } is easy to read than "null".

Once addressed that, we have to be consistent and use an array for chain too.

**Comment by conartist6** [comment]
Hmm, I think in that regard it's good the way it is actually. Named arguments are, by convention, less important than positional ones, so it seems quite odd that a named argument would change the entire behavior of the function. I guess there could be two options: {longest: true, fill: null}, but at that point it's not any shorter or more readable and it breaks convention with Python Rust and Linq, which all have zipLongest.

**Comment by sithmel** [comment]
what about the array of iterables on zip/zipLongest/chain?
The main argument for this is that it would be easy to remember if all 3 are consistent

**Comment by conartist6** [comment]
I thought they were all consistent already, but it appears that chain still is not. I think changing methods to or from an array for reasons of consistency is fine.

The only thing I think is that in considering what constitutes consistency, for the sake of users we might also consider establishing parity with other libraries.

Here's what they do for each of these methods:
Method | RxJS | Immutable
chain | [concat](rxhttps://rxjs-dev.firebaseapp.com/api/index/concat) | [concat](https://facebook.github.io/immutable-js/docs/#/Seq/concat)
zip | [zip](https://rxjs-dev.firebaseapp.com/api/index/zip) | [zip](https://facebook.github.io/immutable-js/docs/#/Seq.Indexed/zip)
zipLongest | [zipAll](https://rxjs-dev.firebaseapp.com/api/operators/zipAll) | [zipAll](https://facebook.github.io/immutable-js/docs/#/Seq.Indexed/zipAll)

**Comment by conartist6** [comment]
Note that they seem to have established API parity with each other already.

**Comment by sithmel** [comment]
Brilliant analysis!
I wondering at this point if it makes sense having the "filler" argument in zipLongest and not just having zipAll that takes iterables like rxJS and Immutable.
I personally don't really have a use case for that. What you usually want is "undefined"

**Comment by conartist6** [comment]
Yeah I agree that undefined usually is almost always what makes sense. I don't have an opinion either way.

**Comment by sithmel** [comment]
ok, I would proceed in removing the filler argument for zipLongest.
I am also tempted at this point in having aliases for chain/concat and zipLongest/zipAll

**Comment by conartist6** [comment]
Ok. Also on the topic of aliases, `concat` should be an alias for `chain`, as that is also the name used by both Rx and Imm.js.

Now that we're removing all extra arguments from `chain`, `zip`, and `zipLongest` should we also settle on not wrapping the arguments in arrays?

**Comment by sithmel** [comment]
I am happy to not wrap if they are consistent :+1:
