### ISSUE TITLE
why entries behave like this?

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#27]
Why to privilege the use of "keys" and "values", even when "entries" is available ?

**Comment by conartist6** [comment]
It's the `reuseEntries` optimization again. If you're avoiding doing unnecessary memory allocation, you don't want to create many of these [key, value] arrays. the `Map.entries` iterator creates n entries arrays for a map of size n. In order provide the `entries` data without allocating those arrays, we must have another way to get that data that does not allocate memory. That way is though the `keys` and `values` iterators, which are present both for `Map` and `Immutable.Map`.

**Comment by sithmel** [comment]
got it, thanks for the explanation
