### ISSUE TITLE
Reduce can't take an initial value

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#30]
I propose what amounts to an overloaded implementation:
```js
reduce(reducer, iterable) { ... }
reduce(initialValue, reducer, iterable) { ... }
// and for good measure
reduceRight(reducer, iterable) { ... }
reduceRight(initialValue, reducer, iterable) { ... }
// ... async
```
This should work because reducer must always be specified. The worst case would be if initialValue was a function, in which case the code would need to distinguish between reducer and iterable, but this seems OK because iterable can only potentially be null or something with [Symbol.iterator], and reducer can be neither of those things.

**Comment by conartist6** [comment]
Reduce should also use the first item of the array as the initial value if it exists, as [`Array.reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) does. This will be a breaking change because when reducers are written using the pattern described in the documentation (below) the default value for `acc` will never be used:
```js
reduce((acc = 0 /* X_X */, val) => acc + val, range(4))
```

**Comment by conartist6** [comment]
I have the implementation of this ready, but I'll wait until you accept the other one. I guess if I committed my in-progress code to branches of this repo instead of to my fork, then I could create PRs between local branches, and thus be able to stack revisions. I'll start doing that in the future, but I'm too lazy in the present.

**Comment by sithmel** [comment]
I am not 100% sure to understand what is missing from the current implementation.

**Comment by conartist6** [comment]
The current implementation has only the reducer function parameter. Using it looks like:
```js
reduce((acc = initial, value) => ...)
```
One problem that is: what if the reduce is called on an empty array? Now instead of the initial value you specified you'll get undefined. That is, I think, why `Array.prototype.reduce` looks like:
```js
[1, 2, 3].reduce((acc, value) => ..., initial)
```
