### ISSUE TITLE
Inconsistent handling of null

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#31]
It's pretty important what constitutes an iterable for the purposes of currying now that null is treated as an empty iterable. Currently if you pass null as an iterable to the various functions in the library, some of them will pass the currying conditional and execute and some will not.

I think standardizing on checking arguments.length would make sense.

This area probably should get some test coverage too.

**Comment by sithmel** [comment]
Definitely to do

**Comment by sithmel** [comment]
The current implementation uses ```iterable==null```. This matches with ```undefined``` too
