### ISSUE TITLE
some, every

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#34]
These are all very common utilities that can be done with reduce but would also benefit a built-in implementation.
I am also thinking a a way to get the kth smallest/bigger with an heap

**Comment by conartist6** [comment]
Yep! Also filterNot is a nice to have.

**Comment by sithmel** [comment]
Some and every implemented in https://github.com/sithmel/iter-tools/pull/37

**Comment by sithmel** [comment]
opening a different ticket for other features
