### ISSUE TITLE
Consider making count do size as opposed to range

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#36]
I'm again thinking about parity with [Immutable](http://facebook.github.io/immutable-js/docs/#/Seq.Indexed/count)

**Comment by sithmel** [comment]
I would rather remove the alias altogether, looks confusing both ways

**Comment by conartist6** [comment]
So there's a reason that immutable keeps it. In some circumstances it knows the size of a sequence -- for example if the sequence has just been initialized from a structure whose size is known. Size should be a property (and noun) thus if size isn't known it just returns undefined. Count is a verb/method, suggesting (and made clear in the docs) that it will consume the sequence just to find out how big it is.

Sequins will follow this pattern, but it doesn't need iter-tools to. Up to you. Is there a particular API you were looking at when you made this where count is a generator not a consumer?

**Comment by sithmel** [comment]
This: https://docs.python.org/2/library/itertools.html

but now it looks like a bad idea

**Comment by conartist6** [comment]
Let's just leave it then. I consider the issue closed. We considered it. It'll get a callout in the documentation.
