### ISSUE TITLE
update typescript definition

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#4]
I am in the process to add many async iterator functions, now that they are supported by V8 :champagne: 

We already have typescript definitions thanks to @kmxz . It would be nice adding the definitions to the new functions (in lib/async).

**Comment by sithmel** [comment]
@kmxz consider it an help request :smile:

**Comment by kmxz** [comment]
I'll be glad to help.

Just give me some time and let me know how would you like to export the async functions in `index.js`.

**Comment by sithmel** [comment]
many thank, @kmxz!
I have just updated the index.js (on master)
I have also changed the arguments of "reduce", the only real breaking change.
Now it can be curried, just like map, filter etc.
