### ISSUE TITLE
How to not use es5

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#45]
The [bug](https://github.com/sithmel/iter-tools/issues/42#issuecomment-410024606) around iterator abrupt termination in loose mode confirms (and makes worse) what we already knew: the library kind of sucks when transpiled to es5. End users who don't need IE support can work around this easily enough by including the `/es2015` paths, but that's 1) a pain, and 2) doesn't work if the including entity is itself another library.

I think the solution is to write a plugin of some sort. I'm taking some inspiration here from [babel-plugin-use-lodash-es](https://www.npmjs.com/package/babel-plugin-use-lodash-es).

Actually a Babel plugin won't work for us because projects are responsible for their own transpilation and thus a library including iter-tools would have to do what we do and output multiple complete copies of their source files and allow the user to choose between them.

A webpack plugin, however, makes a lot of sense. The bundler already goes deep into the module tree. It could look at a a project's `browserslist` as specified in `package.json`, then rewrite imports to include the highest supported version of the files. Libraries would statically include the es5 modules, but those includes would be resolved to the es2015 files if supported. This makes the assumption that if the more transpiled code works correctly in a given situation, the less transpiled code will too (as long as browserslist feature detection isn't lying). Of course users wouldn't be required to use the plugin either, but it'd be quite nice.

**Comment by sithmel** [comment]
The situation with third party imports is messed up.

I think if you are building a library, the only sane solution is to use iter-tools/es2018 and to transpile in your library. It is horrible but I don't know what else you can do.

**Comment by sithmel** [comment]
No activities here for too long. Closing
