### ISSUE TITLE
Support negative indicies for slice.

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#47]
Should match native slice behavior.

E.g.
```js
slice({start: 0, end: -1}, [1, 2, 3]) // [1, 2] 
slice({start: -1}, [1, 2, 3]) // [3]
```

**Comment by conartist6** [comment]
I guess I'm not certain, but if it were to be implemented it would make most sense to implement it using `tee`. It would race ahead on one iterable looking for the end and letting dequeue handle caching, but it would start to yield values from the source iterable as soon as it was sure there were at least n more items in the sequence, where n is the largest negative index.

**Comment by sithmel** [comment]
I would implement it case by case:
* start > 0, end > 0, start > end: return []
* start > 0, end > 0, start < end: current behaviour
* start > 0, end < 0: buffer from "start", return buffer.slice(0, end)
* start < 0, end > 0: buffer from 0 to end. Finish iteration after end + abs(start)
* start < 0, end < 0, start > end, return []
* start < 0, end < 0, start < end. buffer "(end - start) + end" items (using deque) then return the first (end + start) items

**Comment by sithmel** [comment]
Pr is coming

**Comment by conartist6** [comment]
Oh cool. I'd have done it, but my energy is going towards Sequins. I'm now mostly finished adding concrete types -- Map and Set implementations which use the same API as sequences but are subclasses of native Map and Set, plus a List implementation which is not derived from Array. Also I finally got a new job so I'm going to have less time to spend on both projects as of next week.

**Comment by conartist6** [comment]
Oh also, I did a lot of cleanup on the MDN guide to iterators and generators. I think it's significantly less confusing now.

**Comment by sithmel** [comment]
https://github.com/sithmel/iter-tools/pull/48

**Comment by sithmel** [comment]
I feel we are heading to the release with this.
I don't have anything else to add for now
