### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#52]
Deprecate doesn't work in the browser.

I'll fix it in their repo, just want to make sure we're tracking everything that is blocking the 6.x release.

**Comment by conartist6** [comment]
Ugh, actually I think I'm just going to pull out that module. It's only real functionality over console.warn is that it is meant to only warn once even if the deprecated function is used multiple times. Unfortunately that functionality is based on stringifying function.caller, which is horrifying and probably wildly broken across browsers.

**Comment by sithmel** [comment]
I see your PR on deprecate merged, and I have bumped it in master.
I think this can be closed, reopen if I am wrong @conartist6

**Comment by conartist6** [comment]
Yep. Thanks!

**Comment by sithmel** [comment]
It seems there is a bug on deprecate when used with node (it doesn't work with coverage). I proposed a fix here: https://github.com/brianc/node-deprecate/issues/3

**Comment by conartist6** [comment]
Are you sure that's the right link?

**Comment by conartist6** [comment]
Fixed in 026ff8ba80e672990190c40618ed7ec57f0c6fe7
