### ISSUE TITLE
Is it really necessary to run build every single time I run npm install and git push?

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#58]
### Why?

1. It is enough to have build run before `npm publish`, no needs to prolong `npm install`
2. It is enough to have build run in Travis CI, no needs to prolong `git push`

### Proposal

1. Change "prepublish" to "prepublishOnly"
2. Remove "prepush" hook

**Comment by conartist6** [comment]
I think that's probably left over from when there were still build artifacts checked in. I agree with your proposal.
