### ISSUE TITLE
What happened to the unsuffixed files?

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#70]
Previously I had it set up so that you could access the default (es5) implementations using
```js
import map from "iter-tools/map";
```

I would like to have this for Sequins. After thinking carefully about it, I'm almost certain that users would rather I didn't rely on their correct tree shaking setup to not include unneeded files, but rather simply import files within iter-tools.

I can already do this by requiring files in the `/es5` folder, but I don't like that in the long run. Specifically I don't like it because of the planned work on es-retarget, which will handle using less transpiled versions of iter-tools when appropriate. If my library is explicitly importing es5 code it will be pretty misleading when that import statement ends up pulling in es2015.

**Comment by sithmel** [comment]
Do you think it is an acceptable compromise to advise against using the default as it might be subject to change?

**Comment by sithmel** [comment]
No activities here for too long. Closing
