### ISSUE TITLE
es5 code depends on dependency with arrow function (clone-regexp)

### ISSUE THREAD

**Issue by sladiri** [sithmel/iter-tools#72]
Hi, I am probably doing something wrong, but I tried to use this (great library) in a fresh Angular 7 project. TS compiler target is es5. 

I tried
`import { asyncFilter } from "iter-tools/es5";` or just 
`import { asyncFilter } from "iter-tools";`

IE11 shows a syntax error in clone-regexp. Maybe this is a problem with Angular's Typescript setup?

**Comment by conartist6** [comment]
Seems like a pretty straightforward issue. I opened https://github.com/sindresorhus/clone-regexp/pull/4 for you.

**Comment by conartist6** [comment]
As a workaround you can import asyncFilter's module directly:
```js
import asyncFilter from "iter-tools/es5/async-filter";
```

**Comment by sithmel** [comment]
clone-regexp has been designed for working with node (es2015). I don't see the point in setting the transpilation of external deps for a 15 lines module. I got rid of it.

Version 6.1.5 should be ok @sladiri
