### ISSUE TITLE
Adding here a few ideas for new features

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#75]
## Combinatory generators length
It would be nice to have handy functions to calculate the length of a combinatory generator (given the length of the input sequence). This way I can pick the nth item (for example).

## flatten
A simple flatten (only one level), can be useful. For example I could use ```flatten(zipAll(...))``` to interleave many iterators. You can do the same with "chain" and the spread operator, but would require to expand the argument in an array and it would be inefficient

## window
```js
window(3, range(100))
[0, 1, 2] [1, 2, 3] [2, 3, 4] [3, 4, 5] etc.
```
Better to pick up a different name though

## collate
It takes as arguments n sorted iterable. It returns a single sorted iterable.

## Reduce variant
Similar to the reduce but returning a iterable that return the accumulator.
I don't know yet how to call it.

**Comment by conartist6** [comment]
I want a really simple one, perhaps called `when`, which would take a condition and an item, and would emit an iterable of 0 or 1 items depending on the value of condition. It would only be useful to the extent that it was more compact and readable than using a normal ternary.

For example:
```js
[
  ...(condition1 ? [item1] : []),
  ...(condition2 ? [item2] : []),
  // vs.
  ...when(condition3, item3),
  ...when(condition4, item4),
]
```

**Comment by KSXGitHub** [comment]
> A simple flatten (only one level), can be useful.

Why only one level though? ES native's `array.flatten(n)` accept any level.

I suggest this:

```javascript
flatten(iterable) // flatten infinitely (until meeting a non-iterable)
flatten(n, iterable) // flatten n levels
flatten(fn, iterable) // flatten until fn(x) returns false (x is element/sub-element of iterable)
```

**Comment by sithmel** [comment]
This looks a reasonable implementation though: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

**Comment by sithmel** [comment]
Added #79 #80

**Comment by KSXGitHub** [comment]
I may have to correct your TypeScript declarations.

**Comment by conartist6** [comment]
There's nothing conceptually wrong with not treating strings as iterables for the purpose of a flatten, even though they technically are. I'd argue that even a not arbitrarily deep flatten implementation would want to do that. Obviously if you did let flatten into a string it would blow up as the string iterator returns other strings, which becomes an infinite recursion.

As for "all other types" being iterable, I'm sure I don't know what you mean. Almost every type in javascript is derived from Object, which is not iterable, and this is probably a big part of why. That leaves Array, Map, Set, and classes with iterators defined, which are all acceptable things to flatten.

**Comment by sithmel** [comment]
I am undecided on 3 things:

### About strings
I can see 2 possible approaches:
- they are never considered iterables
- they are not considered iterables when length == 1

### About map, set, and others
There are cases where I don't want to flatten a map or a set.

### About passing a function
I can see the positive side. It solves the problem above as I can decide when to flatten depending on depth and item type.

On the negative side, the behaviour diverge from Array.prototype.flat (but this is probably not a big deal).

**Comment by KSXGitHub** [comment]
> On the negative side, the behaviour diverge from Array.prototype.flat (but this is probably not a big deal).

This is a reasonable trade-off I think, as the ability to decide when to flatten is incredibly powerful.

The next problem is how do we gonna invoke the callback function, there're few ways:

```javascript
fn(depth, element) => boolean
fn(element, depth) => boolean
fn({ depth, element }) => boolean
```

**Comment by KSXGitHub** [comment]
> ### About map, set, and others
> There are cases where I don't want to flatten a map or a set.

We already made exception for `string` as it is special. We should treat `Map` and `Set` as any other iterables to stays consistent.

Also, there's a rule of thumb in designing software called [Zero One Infinity](http://www.catb.org/jargon/html/Z/Zero-One-Infinity-Rule.html).

**Comment by KSXGitHub** [comment]
BTW, @sithmel, if you ever decide to change behavior of `flat(iterable)` from `depth = 1` to infinitely flatten, notify me so that I may update the type declarations.

**Comment by sithmel** [comment]
I published iter-tools@6.1.8-next.1 with flat and cursor

**Comment by sithmel** [comment]
Currently working at **merge** and **asyncMerge**:

It reads multiple iterable and uses a function to decide what item to return every time.

it allows to get something like the collate described above

**Comment by conartist6** [comment]
Awesome. As regards flatten, could I suggest that depth 0 does a deep flatten?

Also for the docs, `isNotAnIterableString` is not the right name for the example callback your provide. The function you wrote is `isNotANonIterableString` which I think could be simplified to `isNotACharacter`.

**Comment by sithmel** [comment]
Ok, with "isNotACharacter"

I am not 100% sure about 0 to trigger the deep flatten behaviour.

I think it is more obvious if 0 is "no flatten". You can still use Infinity for deep flatten. Array.prototype.flat works that way

**Comment by conartist6** [comment]
Oooh ok that's fine with me. I think with the callback I can actually just use this flatten implementation for Sequins, which is great.
