### ISSUE TITLE
asyncSlice type signature returns iterable of number

### ISSUE THREAD

**Issue by coder-mike** [sithmel/iter-tools#87]
The type signature for `asyncSlice` returns `AsyncIterableIterator<number>` instead of the expected `AsyncIterableIterator<T>`
https://github.com/sithmel/iter-tools/blob/master/src/index.d.ts#L445

**Comment by sithmel** [comment]
Thanks for spotting it. Merged it.
I am going to release a minor release including this fix and a couple of new features very soon.
