### ISSUE TITLE
Remove precommit hook?

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#98]
For the same reason of https://github.com/sithmel/iter-tools/issues/58

**Comment by sithmel** [comment]
I would leave this here for 2 reasons:
- it is quite fast
- it can save time spotting a problem early on

**Comment by sithmel** [comment]
@KSXGitHub I would consider it if linting time becomes a nuisance.
Does it take a lot on your machine ?

**Comment by KSXGitHub** [comment]
> Does it take a lot on your machine ?

About 5 - 10 seconds.

I have an old machine :)

**Comment by sithmel** [comment]
This is stale. Closing for now
